### ISSUE TITLE
Name style for push_front and all other names defined in language spec

### ISSUE THREAD

**Issue by QinshiWang** [p4lang/p4-spec#1004]
Other built-in functions are named in camel style, e.g. `isValid`, `setValid`, `setInvalid`. Maybe we want to make the change.

@jafingerhut edit to first comment to give a link directly to this comment below, which gives a much more full picture of all names that have snake case, camel case, and other styles in the current language spec.  The three names isValid, setValid, and setInvalid are just the tip of the ice berg: https://github.com/p4lang/p4-spec/issues/1004#issuecomment-1008338434

**Comment by jafingerhut** [comment]
I know there isn't a mountain of P4_16 code out there, but there is a value to maintaining backwards compatibility where it isn't difficult to do so.

Adding new names for things is less disruptive to existing programs, versus removing existing names.  Even adding new names in this case seems fairly cosmetic to me.

**Comment by vgurevich** [comment]
You can also look at #762 

But I have to admit that most probably the train has left the station.

**Comment by jafingerhut** [comment]
In general, I'm terrible at coming up with great names for functions/methods/externs/etc.  But as LDWG members, maintaining backwards compatibility is one good reason to try to come up with reasonable names we are willing to live with long term (i.e. indefinitely, as long as the P4 language is used) when new names are added.  Even deprecating existing names causes churn in developer code that some could consider unprofessional conduct.  Just because some other language/library environments create such code churn, does not mean we should do so.

**Comment by QinshiWang** [comment]
Thanks for the explanation. In my opinion, we'd better keep the old name but advocate a new name that's consistent with the general naming style in the spec.

**Comment by jnfoster** [comment]
+1

I'd like to see is support a uniform style (camel case I guess) and deprecate the old names over time.

**Comment by jafingerhut** [comment]
I promise to get off my soapbox after one more comment on this issue, but I simply cannot understand how deprecating currently defined names in the P4_16 language specification, not because they are functionally broken, nor insecure, nor any other kind of critical reason that one might consider removing a language feature for, but because "we wish we would have named them differently 5 years ago", is possibly consistent with this statement in the P4_16 language specification:

"One important goal of the P4_16 language revision is to provide a stable language definition. In other words, we strive to ensure that all programs written in P4_16 will remain syntactically correct and behave identically when treated as programs for future versions of the language."

In my opinion, part of backing up that statement with actions is sometimes saying, "Yeah, I wish we had done things differently, but it isn't actually broken, so we will keep some of the things the same that we wish we would have done differently."

**Comment by jnfoster** [comment]
Let's discuss this at the next LDWG. I think it needs a community discussion.

I will point out that the pledge we made when P4_16 was released is a bit weaker. We didn't promise strict backward compatibility. We said we'd think hard about breaking changes, aiming to avoid them of course, and provide a migration path... I can pull up my exact verbiage from an old P4 Workshop talk.

**Comment by vgurevich** [comment]
I think that discussing and clarifying the policy on backwards compatibility will be very useful. 

I am not sure whether this particular issue is a good driver for that, though, since nothing prevents us from creating two absolutely equivalent methods (e.g. `pushFront()` and `popFront()`), while keeping the old ones intact. There is no harm in that (unless we worry that it will break programs where someone has already used these names, but then we have a lot more worries on our hands to deal with)

All we should do (if we decide to add equivalent methods with the desired spelling) is to make sure that all the materials promote the new methods and discourage using the old ones, but these old ones can still be available. I mean, this can be done through simple `#define`s if one wants to do that. Five years from now we can discuss deprecating the old methods.

Speaking of capitalization, note that a much more often used name, `NoAction()` which kind of uses CamelCase, but its first letter is not lowercase.

**Comment by jnfoster** [comment]
Proposal: 
- Let's document our naming scheme for the language in the language specification.
- Let's add secondary names for these operations that are consistent with the scheme.
- And perhaps this should be a v2.0.0 feature (so we can nudge programmers toward them more forcefully).

**Comment by jafingerhut** [comment]
I created this PR that adds new names pushFront, popFront, and actionRun, but does not address the method vs. field questions (and I do not plan to address the method vs. field issues, but happy if others do): https://github.com/p4lang/p4-spec/pull/1009

**Comment by jafingerhut** [comment]
I may be missing some, but here are more names that we should think about when deciding what the naming scheme is:

Existing snake_case names:

1. push_front - method name built into language spec
2. pop_front - method name built into language spec
3. packet_in - extern object type name in language spec and core.p4
4. packet_out - extern object type name in language spec and core.p4
5. default_action - table property
6. match_kind - language keyword
7. header_union - language keyword
8. value_set - language keyword

Existing camelCase names:

1. isValid - method name built into language spec
2. setValid - method name built into language spec
3. setInvalid - method name built into language spec
4. lastIndex - field name built into language spec
5. noSideEffects - annotation defined in language spec
6. noWarn - annotation defined in language spec

Not quite camelCase nor snake_case, and perhaps should be considered to add a new name if we decide that all names should be one of those two:

1. NoAction - action defined in language spec and core.p4
2. tableonly - annotation defined in language spec
3. defaultonly - annotation defined in language spec
4. varbit - language keyword / type name defined in language spec
5. lookahead - method name of extern object type packet_in defined in language spec and core.p4
6. all values of error type, which are CamelCase with initial capital letter - constant names defined in language spec and core.p4

**Comment by jafingerhut** [comment]
FYI, if anyone is hoping that I will spend 3 hours proposing rules for what name style should be used in the future for method names, language keywords, extern object type names, etc. so that there is a consistent naming style, I am here to disappoint you.  I will gladly take any such rules that the LDWG work group agrees upon and create a PR for the spec to do that.  But me, personally, I'm content with the names we have now.  Whoever it is that the current state causes them to lose sleep, please go right ahead!

**Comment by mbudiu-vmw** [comment]
I personally think this is a very low priority subject.
Consistency is nice, but humans are flexible and have no problems coping with the existing rules.
Also, please note that many languages mix various styles, for example see the Rust style guides: types use camel case, while methods use underscores: https://sodocumentation.net/rust/topic/4620/rust-style-guide

**Comment by jnfoster** [comment]
As the guilty party who perhaps gave this higher priority than it deserves, I agree with all of this...

**Comment by jnfoster** [comment]
At the 2/7/22 LDWG, we observed that the ship seems to have sailed, due to the export of these names in control-plane APIs. If someone wants to develop a set of conventions for new names, that would be great, but it's low-priority and a future enhancement.

**Comment by jnfoster** [comment]
A suggestion was also made to add a linter.
