### ISSUE TITLE
"optional" match kind is missing from the PSA specification?

### ISSUE THREAD

**Issue by akertesz** [p4lang/p4-spec#1089]
The PSA specification has a section on match kinds, which describes exact, lpm, ternary, range and selector:
https://p4.org/p4-spec/docs/PSA.html#sec-match-kinds

But it doesn't mention the optional” match kind, which appears in psa.p4:
https://github.com/p4lang/p4-spec/blob/main/p4-16/psa/psa.p4#L344

I think that either optional should be removed from psa.p4, or it should be described alongside the other match kinds in the spec.

**Comment by mbudiu-vmw** [comment]
Yes, P4 allows targets to define their own match_kind values. In consequence, the semantics of the new match_kind values must be documented in the target-specific documentation. The P4 designers cannot know all possible extensions that may exist.

**Comment by mbudiu-vmw** [comment]
Your comment applies to the PSA spec, not to the P4 spec; then it is correct.
But I don't know whether the PSA spec you are pointing out reflects the latest changes in the repository; perhaps a new spec will be released soon?

**Comment by akertesz** [comment]
Yes, I'm talking about the PSA spec. It documents all of the match kinds that psa.p4 adds, but omits optional. This seems to me like a clear bug in the _PSA_ spec.

I am looking at the live version of the spec online. 

Also -- I had an offline conversation with @jafingerhut about this, and he agreed this was a PSA spec issue and suggested I file an issue.

**Comment by jfingerh** [comment]
Note: match_kind `optional` has been committed to the files used to generate the PSA specification, with this commit on 2021-Mar-11: https://github.com/p4lang/p4-spec/commit/3676a3c218e5efd3b32560e546084589cd6b1c64

Unfortunately there has not been any new release of the PSA specification document since that commit, so the pre-generated HTML/PDF for released PSA specs do not include it.

We are planning on releasing an updated version of the PNA spec before Christmas 2022.  I will propose to the working group that we also release and updated version of the PSA specification by that date, too, especially since the PNA specification refers explicitly to parts of the PSA specification.

**Comment by jafingerhut** [comment]
I am closing this issue, as the latest committed version of the PSA spec has `optional` added, and it will be part of a released spec before the end of 2022.
