### ISSUE TITLE
range operator semantics is not clear if left > right

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4-spec#1104]
The current specification has this:
```
The set contains all values numerically between the
first and the second, inclusively.
```
and an example of `4w5 .. 4w8` but it does mention the semantics of what `4w8 .. 4w5` would be?
Is it an empty set or the "anti" set of `4w6 .. 4w7` that is the set that does not contain `4w6` or `4w7` but contains the two sets `4w0..4w5` and `4w0x8..4w0xff`?

**Comment by apinski-cavium** [comment]
Or should the set `4w8 .. 4w5` be an error?

**Comment by apinski-cavium** [comment]
If we base it on the constant folding part of p4c, it is the empty set.
```
        if (left->to<IR::Constant>()->value <= cst->value &&
            right->to<IR::Constant>()->value >= cst->value)
            return Result::Yes;
```

**Comment by jnfoster** [comment]
I don't think anything is amiss here, though we could add some text to avoid the way you got tripped up -- i.e., what "inclusive" means in the case where the left value is greater than the right.

The notation for ranges is borrowing conventions from the mathematical notion of an interval. Note that the [Wikipedia Article](https://en.wikipedia.org/wiki/Interval_(mathematics) explicitly calls out `a .. b` notation (e.g., from Pascal) as an instance. 

In this context, the term "inclusive" is usually taken to mean that the interval is closed -- i.e., it includes its end points. In math, this is often written `[a,b]` instead of `(a,b)` for an open interval.

However, if `a < b` then `[b,a] = (b,a) = [b,a) = (b,a] = {}`. That is, an interval is empty whenever the left value is greater than the right.

**Comment by jafingerhut** [comment]
An empty range like 5..4 does seem like a situation where some P4 developers might prefer the option to get a warning if that occurred in their code, since it seems at least somewhat likely to be a bug (although not guaranteed to be a bug, e.g. if they did it intentionally with a range like FOO..4 where FOO is a constant that is sometimes intentionally used to cause an empty range in some compile runs, but a non-empty range in others).

Agreed that it seems reasonable for the language to explicitly allow it and define it as an empty range that contains no elements, and if used in a select expression, would never be selected.
