### ISSUE TITLE
Is auto default action constant or mutable?

### ISSUE THREAD

**Issue by QinshiWang** [p4lang/p4-spec#1113]
When a table does not have a default action, we say the compiler must set `NoAction()` as the default action. In this case, is the default action mutable or constant?

**Comment by jafingerhut** [comment]
I believe that many current P4 implementations default to mutable by the control plane if there is no explicit default_action table property, i.e. if you want it to be immutable, you must explicitly declare `const default_action = some_action;`

**Comment by vgurevich** [comment]
I re-read the spec and it is a little vague there. In fact, it does not really discuss whether it is possible to change the default action via a control plane API :) Neither, by the way does it discuss what other things about a table can be changed. I think this is actually a good thing, because it allows for more possibilities.

I would state that if something is not clearly stated in the program, the implementation has a lot of latitude. For example, if it doesn't say `const`, there is no reason to prohibit something from being changed at runtime. Whether or not this will be possible is another matter. 

Now, this creates an interesting question: do we need to specify if other table attributes are mutable or immutable? What about the key? The list of actions? The size? Just to name a few that we typically think of being immutable, but that do not have to be that way on all the targets.

**Comment by vgurevich** [comment]
@mbudiu-vmw On some targets, run-time API can offer a possibility to use another set of field(s) as a table key. We do not currently think of this and neither it is supported by P4Runtime, but it is possible and then the key becomes mutable.

**Comment by QinshiWang** [comment]
@vgurevich I think it is pretty strange to allow the set of keys or the set of actions to be mutable. Both of them sound like modifying a function (action) at runtime.

**Comment by mbudiu-vmw** [comment]
Indeed, what happens to the existing mapping key-actions in the table when the key fields change?

**Comment by vgurevich** [comment]
@QinshiWang -- why do you find this "strange"? Computers write code all the time. Think about how the compiler creates the code for the P4 program: it creates some code for the table 1, table 2, etc. Depending on the target, it can do it at runtime too. There are devices (non-P4-programmable even, mind you) that do allow table keys to be specified at runtime. Why do you want to artificially limit the possibilities? 

Again, I am not saying that we need to mandate anything -- it is quite fortunate that P4 specification as it is today does not prohibit us from doing these and many more things like these.

@mbudiu-vmw -- such an operation will almost certainly require the table to be empty in order to be possible, but this is OK and is often preferred to program recompilation.

**Comment by QinshiWang** [comment]
@vgurevich Okay. I kind of buy your point now. I think a compiled program is not required to keep keys and action lists still visible. But if it does, it is okay to modify those places as long as we make sure the program still typecheck.

**Comment by vgurevich** [comment]
@mbudiu-vmw -- I totally agree that by default the default action is mutable, but my main question is:
* Which specific part of the P4_16 spec tells us this and how?

So far, I think that this is more of our assumption rather than a formal statement and thus the second question is: 
* Do we need to make a more formal statement about this specific attribute? 

If we were to do that, I think that we are in agreement: this specific attribute is allowed to be mutable by the corresponding runtime APIs. We can also state that not specifying the initial value is equivalent to adding `@defaultonly NoAction;` to the list of actions and initializing the attribute as `default_action = NoAction()`.

And then the third, longer-term question is:
* Do we need to make any additional statements about other table attributes and if so, what should they be?

My personal position is that unless they have an explicit `const` attribute, runtime APIs can do anything that is allowed on a specific target, meaning that the P4 program defines the initial state of the (P4-programmable portions) of the system. A good recommendation would be for the driver to always provide an API that resets each object to its initial state, specified in the program.

**Comment by mbudiu-vmw** [comment]
I changed my mind, I think that if the compiler inserts a default_action, then it should be "const".
The reason is given by this paragraph in the spec:

$> If a table does not specify the default_action property and no entry matches a given packet, then the table does not affect the packet and processing continues according to the imperative control flow of the program. 

If we allow the control-plane to change the default_action this statement is no longer true.
