### ISSUE TITLE
Restrict constant tables to all explicit or no explicit priorities across all entries?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#168]
I would guess that when creating a constant ternary or range table, people would adopt one of two possibilities:

+ No explicit @priority annotations for any entry of the table, allowing the order of entries in the code to specify relative priority.
+ Every entry of the table has an explicit @priority statement.

Allowing a mix of some of each seems only to raise questions of precisely what it means for them to be mixed together in the same table.  The existing example seems to imply that the i-th entry (i starting from 1 and incrementing with each new entry) is the default value of @priority if none is given, and @priority overwrites that, but it wasn't clear from my reading if that is exactly what is intended.

If people think a mix of explicit and implicit @priority values is useful, I don't have a strong objection to allowing them -- it just seems like a poor coding practice that imposes unnecessary mental effort on one trying to understand the precise behavior.

Maybe the summary is: If this is allowed, I want a lint tool that recommends I avoid mixing such entries if it finds I am doing so.

**Comment by jnfoster** [comment]
If I recall correctly, we didn't discuss this at the 4/24 meeting because it seemed like a minor issue that could be resolved offline. Is there more to say, or can we safely close this?

**Comment by cc10512** [comment]
Indeed we have not discussed it. When we discussed it initially, we agreed to keep priorities because control plane APIs do include a priority, and if we are to extend the spec in the future, we should support them. For read-only tables it is not essential to have them explicitly set. So I would be fine with either enforcing uniformity (all with priorities or all without) or removing priorities from the current spec and add them later when we add runtime entries (if ever). I propose we take a vote at today's meeting, and then I will patch the spec.

**Comment by jnfoster** [comment]
Sounds good, I will add it to the agenda.

-N
