### ISSUE TITLE
Complexity

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#217]
This claim is wrong.

> P4 is not a Turing-complete language. 

Given a sufficiently powerful extern (e.g., arbitrary precision integers) it's trivial to encode a Turing-complete formalism into P4 parsers.

This claim is also potentially misleading:

> In fact, assuming a fixed cost for a table lookup operations and interactions with extern objects,
> all P4 programs (i.e., parsers and controls) execute a constant number of operations for each byte > of an input packet received and analyzed.

It requires reading "P4 program" as a single parser or control, and not an instantiation of an architecture. Note that in the presence of recirculation, one can write programs with arbitrary complexity, or even non-terminating programs.

**Comment by jafingerhut** [comment]
I think in the sense in which they were intended, they are useful things to state about the intent of the design of P4.

I mean, if we want to be pedantic, every computer is a finite state machine, and not Turing complete :-)

The first issue could be made slightly more precise with 'P4 (without externs) is not a Turing-complete language'.

The second could be made more precise by excluding recirculate/resubmit/etc.

**Comment by vgurevich** [comment]
I think that there is a substantial difference between parsers and controls and therefore putting them together is what probably leads to the confusion.

Controls are probably "easier" in that they can express only the "straight" flows, i.e. only those that can be represented with a DAG. This is really the design intent and explains the absence of loops, recursion, etc. 

Parsers are much trickier, since they can easily have loops that can't be unrolled. They are  Turing-complete as Nate showed some time age. In the real hardware they are, indeed,  a limiting factor -- I'll talk about that in the training presentation.

**Comment by mbudiu-vmw** [comment]
This is not the time to be pedantic. The essence of P4 is constant work/byte of header, this is the best way to describe how P4 is different from other languages. If you want to take the paragraph out it's fine, one can implement a compiler even without that bit of information, so it is not necessary as part of the spec.

Vladimir, if you assume that all externs do O(1) work per method invocation and use a constant amount of resources, declared at compile-time, which are very reasonable assumptions, especially for a Tofino-like system, then the parser is a finite-state machine. The Turing machine tape is very short for P4 programs, so they are much closer to finite-state than Turing machines.

**Comment by vgurevich** [comment]
@mbudiu-vmw,

I agree -- this information is not needed for the compiler implementation. But, it is definitely nice to put some limits on what we think can or cannot be added to the language.

I also agree that "constant amount of work per processed byte" is the limit for P4 programs. 

The question is: given the fact that many HW targeted implementations can and should achieve "constant work per packet" (rather than per byte) limit, should we articulate that goal or not?

**Comment by jafingerhut** [comment]
@vgurevitch - "constant work per byte processed" combined with "at most a constant number of bytes can actually be processed by any P4 program" (limited by how deep that particular program's parser can parse, which is always a compile time constant) adds up to "constant work per packet".  Saying all of that explicitly is fine, if people want it in the spec, but the first two give a little more information than the 3rd statement alone.

**Comment by jnfoster** [comment]
Fixed by #245. Waiting to merge that since @mbudiu-vmw has the token to detangle some conflicts, but closing this issue.
