### ISSUE TITLE
Question: Motivation for conditional assignment behavior with header unions?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#231]
I think I understand the proposed behavior from the spec pretty well, and I am not proposing changing it.

Note: Example in question of next paragraph was originally phrased incorrectly, then later corrected.

What I do not understand is _why_ it is proposed to be this way, i.e. why is it considered important/useful that if you do an assignment `u.hi = hi;`, and right-hand side `hi` is invalid, that the assignment make absolutely no change to the state of the variable u?

Why is that considered superior to defining it as "u becomes invalid for all member headers, including hi"?

**Comment by mbudiu-vmw** [comment]
Whatever it is, it should correspond to a field-wise copy, including the "copy" of the invalid bid.
A third possible behavior is to produce not an invalid result, but an undefined result.

**Comment by jafingerhut** [comment]
@mbudiu-vmw Not sure if you have read the behavior of `u.hi = hj;' in the spec for a header union `u` and an invalid header `hj`, but it is defined to be a no-op if `hi` and `hj` are different members of `u`.  Not a copy of bits or fields, but an actual no-op.  `u.hi = hi;` can be implemented by bitwise copying in an implementation, unconditionally.

**Comment by jnfoster** [comment]
@jafingerhut I don't believe there was a deep reason for defining the behavior this way. The semantics you propose is certainly simpler to describe ("just copy") and simpler from an operational perspective. I wouldn't be opposed to adopting it. If you want the old behavior, you could always use a conditional -- and that actually seems more consistent with a "pay-as-you-go" approach to cost.

And even though it's the 11th hour, I think we could make the change since there is a way to emulate the old behavior and this feature is not yet in use. Per our guidelines we would need to use our judgement in classifying this as a technical bug fix vs. a major language change, and we should notify p4-design.

**Comment by jnfoster** [comment]
Hi Andy,

After having another pass over the material, I think here's the rationale:
