### ISSUE TITLE
Targets vs. architectures

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#237]
In a number of places we say that targets may impose additional restrictions---e.g., multiplication only with powers of two, forbidding shifts by large values, masks with compile-time known values, etc.. I think we really mean that architectures may impose additional restrictions. Agree?

-N

**Comment by cc10512** [comment]
Although I'm inclined to say yes, because only architectures are visible to P4, backends for certain targets may impose additional restrictions even when implementing the same architecture. Note that some of these restrictions are more fine grained than the "programming model" that the architecture defines. 

That is, an architecture may not impose all the restrictions that a target may impose. The target may implement the functionality specified by the architecture for a subset of the possible inputs.

**Comment by jnfoster** [comment]
I agree with this and I think we already cover this when we discuss conformance of a target.

So I think the AI is to change most phrases of the form "targets may..." to "architectures may..."

**Comment by vgurevich** [comment]
In the training presentation I widely use the term "platform", which is defined as "an architecture implemented on a given target". This term might might help in the cases, where we understand that the architecture exposes something that is fairly target-dependent.

**Comment by mbudiu-vmw** [comment]
We are way past the deadline for finishing this. Rushing such changes will only make the document more confusing. If these edits were to be done, they should have been done a long time ago.

**Comment by jnfoster** [comment]
I changed most of these over the weekend, to make it consistent with the terminology we agreed upon during design meetings last fall and have already defined in the early sections. I agree with @mbudiu-vmw that it's too late to introduce a new term like platform.
