### ISSUE TITLE
Lookahead might be a little restrictive

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#280]
In the section 11.8.3 (Lookahead) we have the following definition:

```
T packet_in.lookahead<T>() {
   bitsToExtract = sizeof(T);
   lastBitNeeded = this.nextBitIndex + bitsToExtract;
   ParserModel.verify(this.lengthInBits >= lastBitNeeded, error.PacketTooShort);
   T tmp = this.data.extractBits(this.nextBitIndex, bitsToExtract);
   return tmp;
}
```

Basically, it says that in order to use lookahead, the packet should have at least sizeof(T) bits in it. However, in most use cases only the first few bytes of a lookahead might be used and then this definition becomes problematic. Consider, for example, the following case:

```
header ipv4_t {
    bit<4> version;
    bit<4> ihl;
    . . . 
}

state check_ip_version {
    transition select(packet.lookahead<ipv4_t>().version) {
        4: parse_ipv4;
        6: parse_ipv6;
        default: parse_inner_l2;
     }
}
```
Spec-wise, this construct will fail if there is less than 20 bytes remaining in the packet (and if ipv4_t contains `varbit<320> options;` then it gets even worse. However, in reality we only need 4 bits or so and I think that most real-world implementation will not attempt to extract the whole header for the purposes of a lookahead.

Yes, I know, there are other ways to achieve the same effect, e.g. `packet.lookahead<bit<4>>()`, etc.

**Comment by cc10512** [comment]
Given that the lookahead is typically used to figure out what to extract, I think it is entirely reasonable to extract only the version using ```packet.lookahead<bit<4>>()```. Moreover, it is not clear what is it that you're proposing to change in the spec.

**Comment by jnfoster** [comment]
I agree. This seems like a good insight for a programmer's guide, but the
spec is OK.

N

**Comment by vgurevich** [comment]
@cc10512 ,

So the problem is that if based on the result of the lookahead I want to extract a shorter header that what was used to specify the lookahead type (or not to extract anything at all), the spec will still direct me into the reject state and that's not nice.

**Comment by jafingerhut** [comment]
@vgurevich I understand that this might be a little bit inconvenient to use things like packet.lookahead<bit<4>>() when you have the field in the header you want already defined.  Another alternative is to define a header that is the prefix of the header you want, but contains only the minimum subset of fields you need to extract.

The main issue with doing it any other way, is that unless the maximum lookahead bits is explicitly specified by the programmer, we would be relying upon the quality of a compiler's automatically inferring the number of bytes needed for that particular lookahead.  This is easy in the common cases you are probably imagining, but once you throw arbitrary assignments, sub-parser calls, etc. into parser states, it gets trickier, and I would expect different compilers to vary in their quality here.  That would be another source of P4 program non-portability.

One thought that occurred to me that might be reasonable to add to the spec would be a 1-argument lookahead that indicated that number of bits to look ahead, e.g.:
```
packet.lookahead<ipv4_t>(4).version
```
Such an expression would have a defined value if the field accessed is within the number of bits extracted, otherwise it would be undefined.

**Comment by jnfoster** [comment]
It looks like this conversation reached a resolution. I'm closing this. Feel free to re-open if it needs further discussion.
