### ISSUE TITLE
[PSA] count() operation on counters

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#308]
For a 'bytes' or 'packets_and_bytes' counter type, count() having a
second parameter 'increment' that specifies how much to add to the
byte counter is a very good thing.  It is best if the P4 program has
the flexibility to choose the length in bytes it wants to use for the
packet, e.g. in case it is increasing or decreasing the received
packet's size before transmitting it.

For counters that have type 'packets', presumably every call to
'count' will add exactly 1, yes?  In that case, having a separate
method call that only takes an 'index' parameter would be best, since
the 'increment' parameter value would be ignored, anyway.

**Comment by jafingerhut** [comment]
Proposal:

+ For direct counters, allow the counter_type to be 'packets' only -- do not support counter_type 'bytes', nor 'packets_and_bytes'.  If you want those counter types, use a regular counter instead of a direct counter.  (If someone wants to allow those counter types for direct counters, then they must define what value will be added to the 'bytes' counter when a packet searches the table.)  Remove method 'count()' from the extern object definition, if there is no reason for it, e.g. if it is automatically called whenever the corresponding table is searched, and should not be called from the user's P4 program directly, then having such a method only leads to confusion for why it is there.

+ For 'regular' counters (i.e. not direct counters), only support the existing 'void count(in S index, in W increment);' method if the counter_type is 'bytes' or 'packets_and_bytes'.  The value 'increment' is the value added to the bytes counter updated, and 1 is always added to the packets counter.  If the counter_type is 'packets', add a new method 'void count(in S index);' that always adds 1 to the counter specified by 'index'.

+ Do we want to specify that hardware counters are all saturating, i.e. 'stick' at their maximum values rather than wrap around?  If we want the option to have either saturating or wrapping options, it would be good to put that in the PSA spec.

**Comment by vgurevich** [comment]
I would make even a stronger statement -- we should probably start defining packet counters only.

Byte counters (or packet-and-byte) should be defined separately and they will probably be quite restricted, based on what we know about high-speed pipelines and their implementations. The reason I am saying that is because more often than not, packet length is not even available during packet processing (especially at the ingress). Also, it can change when headers are added or removed. Usually, HW uses special mechanisms to account for that that are not necessarily flexible or compatible across multiple different implementations.

**Comment by jafingerhut** [comment]
@jnfoster @vgurevich @cc10512  (others welcome to answer -- I just want to call attention to the questions below to these people, who expressed interest in this topic)

Before the PSA working group meeting on 2017-Jul-10, I had previously believed (perhaps mistakenly) that having a direct counter associated with a table meant that even if the P4 program had no explicit count() update method calls in the code, they would automatically occur whenever the table had an apply() method call performed on it.

During the meeting, someone mentioned that this was not the case.  Even if you have a direct counter associated with a table, the counter state is only updated via an explicit method call in the actions for that table.  If an action for that table does _not_ call the count() method, then no state for that direct counter extern will be updated when table entries with that action associated with them are matched.

If this is true, what is the intended distinction between a direct counter, vs. a 'normal' counter?  Is it that a direct counter can _only_ be updated in the actions for the table that it is associated with, whereas for a normal counter, it can be updated in the actions of more than one distinct table?

Is that distinction considered sufficient reason to have a separate notion of a direct counter vs. normal counter?  Or would only having a 'normal' counter be enough, and we can dispose with the idea of direct counter, for simplification of the PSA spec and implementations of it?

If there is an advantage to having a separate direct counter extern, someone mentioned during the meeting that the intended way to 'associate' a direct counter with a table is by assigning a value to a table attribute with a particular name.  Does anyone have an example snippet of P4_16 code for a table and an associated direct counter that shows how this is intended to be done?  I would like to include such an example in the PSA spec.

**Comment by ChrisDodd** [comment]
For a direct counter, the count method has no index parameter -- there's one counter associated with each action and that counter is bumped when the action calls ctr.count().  On some hardware it might be possible to do that conditionally.

For a normal counter, the count method has an index parameter that specifies which counter in the counter array gets bumped.  So you call ctr.count(idx) where idx might come from packet data or might be an action parameter.  Sometimes one refers to these as indirect counters.

**Comment by jafingerhut** [comment]
@ChrisDodd Thanks for the distinctions you gave.  I feel like slapping my forehead due to forgetting such basic distinctions.  Will include brief reminders of these facts in my proposed changes to the PSA.

Still hoping someone has a P4_16 code snippet giving proposed syntax for instantiating a direct counter, with a proposed table attribute, if one is intended to be involved.

I will assume for now that the count() method must be explicitly invoked in the P4_16 source code in order for any update to occur, i.e. some actions for a table with an associated direct counter are permitted to make no such counter update, if the P4 program writer wishes.

**Comment by hanw** [comment]
How about something along this line?

```
extern counter<I> {
  counter(counter_type_t type, @optional I instance_count);
  void count(@optional I index);
}

control ingress() {
    counter() cntr;
    action call_count() {
         cntr.count();
    }
    table test {
         actions = { call_count; }
         key = {...}
         implementation = cntr;
    }
```

**Comment by jafingerhut** [comment]
@hanw Thanks.  @optional is a relatively recent addition to the p4c compiler, as far as I know.  It is definitely not mentioned in the P4_16 v1.0.0 spec.  Are you proposing that @optional should be supported by all P4_16 implementations that support the PSA?

**Comment by hanw** [comment]
The `@optional` annotation is a stop-gap until we can have named parameter in p4-16. I am not proposing `@optional` should be used in PSA. A better solution is to support named parameter in the language. With `@optional` or named parameter, we can use the same counter extern for both direct and indirect counters. Without `@optional`, we will need to define two separate externs, as in the current PSA draft.

What I am trying to show in the example is how to instantiate a direct counter in a table (regardless how direct counter extern is defined.)

**Comment by jafingerhut** [comment]
This PR proposes relevant changes: https://github.com/p4lang/p4-spec/pull/348

**Comment by cc10512** [comment]
@jafingerhut AFAIK the current BMv2 implementation requires explicitly calling count in an action(). @antoninbas should confirm.

**Comment by mbudiu-vmw** [comment]
Optional is not the same, since it allows both calls with and without argument for the same instance.
You could consider a countBytes() method.

**Comment by jafingerhut** [comment]
@mbudiu-vmw Do you see any problems if we have the following method signatures for a Counter extern?

+ a 2-argument count(index, add_value) method that adds 'add_value' to a counter, and also
+ a 1-argument count(index) method that behaves the same as count(index, 1)

That is what is in a current proposal for updating the PSA, but would to know if making those the same name would be a problem.

**Comment by vgurevich** [comment]
Personally, I am not in favor of merging direct and indirect counters.  There is some commonality to be sure, but ultimately they are fairly different objects not only in the data plane (as is evidenced by this additional parameter), but in the control plane also. 

I suggest keeping them separate. Having these optional arguments, overloaded method signatures and such seem to confuse us more than it is going to help the users.  We can always merge them later, but splitting a single counter object into two different ones will be very painful.

**Comment by jafingerhut** [comment]
@vgurevich After @ChrisDodd reminded me of the fundamental difference between direct and indirect counters, I agree they should be kept separate.  Please take a look at the proposed PR and let me know what else is wrong with it :-)

**Comment by antoninbas** [comment]
Not sure if it is relevant to the discussion but @cc10512 mentioned me so... in bmv2 direct counters do not require calling count explicitly in the action, because this is the way P4_14 works. The simple_switch `count` action primitive (https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/primitives.cpp#L291) always takes an index because it can only be used for indirect counters.

**Comment by mbudiu-vmw** [comment]
Extern methods cam be overloaded if they have a different number of arguments. How optional arguments will impact this is not clear.

**Comment by jafingerhut** [comment]
I believe that the latest version of the PSA draft Counter/DirectCounter section addresses this issue.  If anyone interested has comments on that latest version, they can open a separate issue for it.
