### ISSUE TITLE
[PSA] packet length for meter execute()

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#312]
For meters, the length of the packet used for meters with type 'bytes'
must be specified.  Even better, add a 'length' parameter to the
'execute' call that lets the P4 program author choose what length to
use.  That will lead to the same issue for direct meters as was
mentioned for direct counters above, with the same solution -- don't
use direct meters when you want to choose a custom length.

**Comment by jafingerhut** [comment]
Proposal:

+ For meter type 'packets', change the current method definition 'MeterColor_t execute(in S index, in MeterColor_t color);' to one of these

(1) void execute(in S index, out MeterColor_t color)   (note: 'in' changed to 'out' for 2nd arg)
(2) MeterColor_t execute(in S index)     (note: remove 2nd arg - color is return value)
(3) something else, after someone explains why returning a MeterColor_t _and_ accepting one as an argument is useful.

+ Once the previous point is decided upon for meters with type packet, add a new method with the same signature for meters with type 'bytes', except that it has one additional 'in bit<16> num_bytes' parameter that is the length in bytes to use for the update operation.

+ Only support 'packet' type meters for direct meters, not 'bytes'.  Clarify in the spec how the MeterColor_t value is made visible to a P4 program after it does a <table>.apply() operation on the table for which the direct meters are directly 'attached to'.

**Comment by vgurevich** [comment]
@jafingerhut 

Totally agree that if a method computes something (e.g. MeterColor_t) is should return it (rather than using an "out" parameter), since it facilitates composability (e.g. the result can be used in an expression).

Some thoughts on the "length" parameter...

Why don't we start with just packet-based meters and counters, because the byte-based ones are quite difficult.

 In many cases packet length is not clear at all. For example, the ingress control can easily finish processing before the whole packet arrives and its length becomes known. In case of cut-through, the same can happen even at the ingress. Packet length in bytes is also affected when headers are being added/removed in the controls. 

The same applies to the counter discussion in #308

**Comment by jafingerhut** [comment]
"Why don't we start with just packet-based meters and counters, because the byte-based ones are quite difficult."

The read-modify-write part of the update in hardware isn't very difficult at all.  It is just a 16-bit add/subtract to a number of tokens, instead of increment/decrement.

Agreed that cut-through makes knowing packet lengths 'interesting', but even there one might usefully calculate them from things like IPv4 total length field in the header.

I don't think it makes sense for an architecture to automatically choose a packet length for you -- it makes more sense to me for the length to be calculated explicitly in the P4 program, so it can handle any of the various tunnel encap/decap/etc. cases that might cause the length on which you want to do metering to change.

**Comment by jafingerhut** [comment]
This PR for Counter and DirectCounter changes doesn't make any changes for Meter and DirectMeter, but if those changes are considered reasonable for counters, similar style changes could be made for meters: https://github.com/p4lang/p4-spec/pull/348

**Comment by jafingerhut** [comment]
This PR has been merged into the PSA, and documents explicitly that like Counters and DirectCounters, Meters and DirectMeters use a packet length defined by the implementation that is not subject to control by the P4 program: https://github.com/p4lang/p4-spec/pull/379
