### ISSUE TITLE
[PSA] "write only" methods

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#316]
"Write-only" methods. This particular choice will force most programs (except for the trivial ones) to keep separate metadata to keep track of the port/multicast_group/drop decisions and use these primitives only at the very end of the ingress control. For example, very often an ACL might want to match on an egress port for a unicast packet. Or, sometimes, an ACL might want to reverse a drop() decision. Neither is possible with the current set of PRE methods without having additional metadata carried alongside.

**Comment by jafingerhut** [comment]
I think a better name to describe this isn't "write only", but "cannot be undone".  From all appearances in the spec, if you do a drop() action, it cannot be undone later.

I am sympathetic to @vgurevich's desire for defining what happens to a packet via explicit metadata fields.  Such fields would be both readable and writable throughout the ingress control block, and actions could be 'undone' if desired.  The behavior could be precisely specified in terms of pseudocode, e.g. something like:
```
if (std_metadata.drop == 1) {
    packet is dropped, i.e. no packet is written to the PRE packet buffer, and thus no packet will be sent to the egress control block later due to this ingress control block processing
} else if (std_metadata.multicast_group != 0) {
    // description of multicast behavior here
} else if ... more conditions here ...
```

**Comment by cc10512** [comment]
Most of the functions in the PRE do allow 'undo' by simply setting a new value to the port/group/etc. And since you are setting a port/group/etc to a value, that value comes from variable that one can match against (or a constant). The style of programming that you give as an example encourages using global structures that the architecture needs to maintain in metadata -- for all the metadata possible, not just the one it is used (and then of course, to rely on the compiler to eliminate the unused metadata). It seems to me that this is against the trend in P4_16 of localizing state. Moreover, in your example you have a 1 bit drop. Some architectures may use several bits to implement a variety of drops which won't be expressible in the PSA standard metadata.

Undoing drop is indeed not possible in the current draft. However, I'm curious to hear if this is such a big issue. If ACL wants to undrop, why don't we check the negated condition and drop at that point. I do have a hard time understanding how come you made a decision to drop the packet and now that condition no longer holds. Is this just an artifact or a real need?

**Comment by jafingerhut** [comment]
Whether all of these things are in visible metadata fields, or in 'hidden state' inside of the PRE object, the state is 'global to the ingress control block'.  Neither approach localizes this state more than the other, as far as I can tell.  One approach makes the state accessible only via method calls, the other via metadata variables.

That said, I don't know of a strong need to reverse drop decisions made earlier.  If someone wants to, they will have to maintain their own metadata about the decision, and delay calling drop() until the end of the ingress control block, as @vgurevich noted.

**Comment by cc10512** [comment]
Yes, in the end it is a matter of taste. It would be great if other folks express their opinions one way or another and we can vote on the direction if we can not reach consensus online.

**Comment by vgurevich** [comment]
There are a couple of issues at hand:

1. Functional completeness. To me, every time I see set() without a get() and reset() it is usually a red flag
2. Efficiency. More complex programs that also need more resources will be required to carry extra metadata and execute additional code at the end to perform the resolution and call the required methods at the very end of the pipeline. Yes, I know that portability might have a certain price, the question is should we start paying it even in the simple cases
3. Delayed effect. When someone does "pre_metadata.drop_flag=1;" I think it is quite clear that the packet is not going to be dropped right away. When you do "pre.drop();" the impression is quite different. Yes, it will be documented, but still. Certain language constructs carry certain "first impressions" with them
4. More difficulties for platform-independent tools. For example how can a tool find out if there is a dependency between tables that call these various primitives?
5. A slightly funky interaction between them. For example, if one wants to ensure that the packet actually is sent to port, they need to do something like
```
action real_send_to_port(in PortId_t port) {
    pre.multicast(0);
    pre.send_to_port(port);
}
```
This raises a lot of questions (since actions are executed sequentially)... Also, I assume that multicast() and send_to_port() do cancel drop(), but I am not sure that has been mentioned explicitly.

The explicit metadata sure has its own set of problems, especially for implementations that decide to structure their metadata differently. The atomicity problem (5) will still be present too. However, they will be more visible and everyone will be able to see what's happening (including both tools and humans). In addition to that, it will lead to more efficient more "creative" code, although one can argue that in real data plane programs people will tend to abstract all these anyway...

**Comment by jafingerhut** [comment]
Perhaps this issue can be closed now?

**Comment by vgurevich** [comment]
@jafingerhut ,

Given that we switched to "intrinsic metadata is the primary source of truth" approach, I agree -- we can close.
