### ISSUE TITLE
[PSA] What if no valid forwarding operation is specified?

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#317]
What happens if neither send_to_port(), nor multicast(), nor drop() are called?

What happens if port, specified in send_to_port doesn't exist on a given device?

**Comment by jafingerhut** [comment]
"What happens if port, specified in sent_to_port, doesn't exist on a given device?"

Sorry, I can't resist proposing (1) as a straw man.  Too much discussion of undefined behavior in P4_16 ...

(1) The device's behavior is undefined, and it does not have predictable behavior until it is reset.

(2) the packet goes out a port number with an undefined value

(3) the packet is discarded, and an implementation should make available to control software both a saturating counter that counts the number of such discarded packets, and a error status value that records the first invalid port number for such a discarded packet (first since it was last "read & cleared", after which it is 'armed' again).

I'm in favor of (3) among those choices.

**Comment by vgurevich** [comment]
I am totally in favor for safely dropping a packet if nothing has been specified. It basically means that the semantics of an empty P4 program is defined (as a blackhole). This is the safest option. Counters are fine, but optional. The most critical thing is that there are no adverse consequences.

Same way, I think it would be nice if we mandate that sending a packet to a non-existent port is also a safe drop. 

With regards to undefined behaviors. In my view, the bar for Portable Architecture is somewhat higher. The reason is that "the buck stops at the architecture". We defer a lot of things to the architecture and if the architecture is not portable in itself, language portability does not matter as much -- the program is not going to be portable anyway. But, the portable architecture is a totally different beast -- we want these programs to be really portable. That's why the bar is higher, at least in my opinion.

**Comment by jafingerhut** [comment]
At the 2017-Jul-24 PSA work group meeting, this issue was raised, and there was general agreement that the default behavior for a packet on ingress should be to drop it, until and unless some other action is explicitly invoked.

**Comment by jafingerhut** [comment]
This PR has been created, that among other things specifies behavior such that if there is an empty ingress control block, the packet will be dropped, with no clone or resubmit action performed: https://github.com/p4lang/p4-spec/pull/384

**Comment by jafingerhut** [comment]
PR #384 has been merged in, and hopefully makes it clear from the pseudocode behavior after Ingress, and the default values of the ingress metadata involved (clone=false and drop=true), that if the ingress control block does nothing, the predictable resulting behavior should be to drop the packet.

TBD: It doesn't yet say anything about what happens if the egress_port is a value that doesn't exist on the device.  It should.

**Comment by jafingerhut** [comment]
This PR addresses what I believe is the last remaining part of this issue, which is specifying that if egress_port has a value not corresponding to any port in the implementation, the packet will be dropped: https://github.com/p4lang/p4-spec/pull/441
