### ISSUE TITLE
[PSA] index out-of-bound error

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#323]
Indirect counters, meters and registers. What happens if index is out-of-bounds?

**Comment by jafingerhut** [comment]
Initial proposal, but I would love to hear @vgurevich's take on this one, too.

For counter updates and register writes, no counter or register state will be updated.

For register reads, an undefined value will be returned as the result of the read.

For meter updates, no meter state will be updated, but the 'metering result' (e.g. red/yellow/green, or conforms/exceeds/violates) will be an undefined value.

In all cases, it is an optional enhancement if the system counts the number of times this happens, and records an error status register for the first such event (since it was last read&cleared) containing some id indicating which set of counters, meters, or registers on which this occurred, and the out-of-bounds index value.  The system may do so independently for each set of counters, meters, and registers, or aggregated across the entire P4 program.

**Comment by vgurevich** [comment]
+1

**Comment by jafingerhut** [comment]
This PR proposes relevant changes, but only for counter, not for meters or registers: https://github.com/p4lang/p4-spec/pull/348

**Comment by samar-abdi** [comment]
I am assuming the counters/meters are being referred to from the P4 program? If so, does it make sense to introduce error return values for the extern functions? I would be a bit nervous about undefined meter color if the index is incorrect.

**Comment by jafingerhut** [comment]
At the 2017-Jul-24 PSA work group meeting, there were several minutes of discussion on the undefined behavior remaining in this proposal, namely the register read value returned, and meter color returned, being undefined values.

Some in the meeting were asking about returning or saving some kind of error status.  It wasn't mentioned during the meeting, because I didn't think of it then, but note that with the existing P4 language you could implement this yourself, like so:

```
    const bit<10> N_REGS = 768;
    bit<10> idx;
    Register<bit<16>, bit<10>>(N_REGS) r1;
    bit<16> tmp;
    bit<1> r1_idx_err;

    r1_idx_err = 0;
    // ...

    
    if (idx < N_REGS) {
        tmp = r1.read(idx);
    } else {
        tmp = <some default value>;
        r1_idx_err = 1;
    }

    // ... code here that could use tmp, assuming the default value above was considered by
    // the program author to be safe to use.

     // alternately, one could check the value of r1_idx_err and do whatever one wanted to,
     // e.g. drop the packet, send a copy of it to the control plane CPU with a software-defined error
     // header that included some id naming 'r1', and containing the bad idx value, etc.
```

**Comment by jafingerhut** [comment]
This PR proposes relevant changes for meters, including example pseudocode for avoiding the undefined behavior for the Meter execute(idx) call for a value of idx that is out of range: https://github.com/p4lang/p4-spec/pull/379

**Comment by jafingerhut** [comment]
This PR: https://github.com/p4lang/p4-spec/pull/380
proposes relevant changes for registers.  It does not have its own unique example for how to avoid the undefined behavior, instead referring to the one added recently in the Meter section.

**Comment by jafingerhut** [comment]
All of the PRs mentioned above have now been merged in, so now the PSA draft document describes all of the pieces of the proposal in this comment above: https://github.com/p4lang/p4-spec/issues/323#issuecomment-312400013

They are spread across the counter, meters, and registers section of the document.
