### ISSUE TITLE
[PSA] Number of action profile members per group in action selector

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#358]
The action_selector extern defines a max_size. I believe this max size refers to the number of action profile members + groups that can be programmed. Can we please clarify?
Also, we will need a way to specify the max number of action profile members per group.

**Comment by antoninbas** [comment]
AFAIK, the size is intended to be the total maximum number of action profile members (the number of groups is irrelevant).
I would also like to have the ability to specify the maximum number of action profile members per group in the P4 program, when instantiating the action_selector. If enough people are interested, it may make sense to have it be a constructor parameter, instead of relying on an annotation of some kind.

**Comment by samar-abdi** [comment]
The consensus is to define max number of members and groups in the extern specification. Max is to be treated with a grain of salt. If the target supports a selector with more capacity than specified in the selector instance, then behavior for exceeding the max at runtime is undefined. If the target cannot support the specified max, the P4 program will be rejected.

I am closing this issue. If anyone has objections, please reopen.
