### ISSUE TITLE
[PSA] Bridged metadata

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#404]
In P4_14 all metadata is global and can be referred to both in ingress and egress control. The set of metadata fields that are referred to in both controls have to be carried over through the PRE somehow and are referred to as Bridged Metadata.

In the original PSA spec, we used the same set of H and M as both outputs of the ingress control and inputs to the egress control. Again, the assumption was that they would somehow be carried over through PRE (with, probably, another assumption that the compiler will figure out how to carry only the minimally required set). 

Now, with the introduction of ingress parser and egress deparser and separating H and M into IH/IM and EH/EM, we need to decide how to define whether there is metadata that is automatically  passed from ingress() to egress() control (or from ingress() control to egress parser or from ingress deparser to egress parser).

**Comment by jafingerhut** [comment]
At least one possible approach is to specify that there is always _no_ bridged metadata, i.e. all metadata that is accessible in the egress pipeline is exactly and only that metadata which is initialized in the egress parser, or the egress control block.  If a P4 programmer wanted some metadata to be passed from ingress to egress, they would do so explicitly by adding a header to the packet containing the values of those metadata fields in the ingress deparser, and parse that header in the egress parser.

If you have other ideas for defining what metadata would be bridged, and what would not, please propose it.  My current thinking is that it would be preferable that the bridged metadata could be determined in a straightforward manner from examining the P4 source code.  Perhaps P4_16 annotations might be an appropriate mechanism for making these things explicit?

**Comment by vgurevich** [comment]
Yep, that's the current thinking, although there are some nasty details that need to be resolved. 

My main concern is that this is so much more complicated compared to P4_14 and hence it's more error-prone as well...

**Comment by jafingerhut** [comment]
Can you give an example or hint of a nasty detail needing resolving with the 'no bridged metadata' approach?  It seems to me that it avoids nasty details in specifying the behavior pretty well -- all egress metadata is undefined until explicitly initialized by an assignment statement in the P4 source code, except for the handful of intrinsic metadata fields that PSA promises to initialize, like egress_port etc.  User-defined egress metadata is pretty similar to user-defined ingress metadata then, yes?

**Comment by vgurevich** [comment]
@jafingerhut ,

The current V1 (and P4_14) approach easily pulls fields from unrelated metadata structs into a single list at the end of the ingress and easily spreads the fields into multiple unrelated metadata structs at the egress. In the new approach everything has to be done manually. 

If you think about the details of the process (if you were to code it manually), these unrelated metadata fields need to be copied into a header somewhere before or in the deparser, since headers are the only things we can deparse so far. However, headers are much more restrictive than the metadata, because they define the layout of the fields on the wire. Determining a layout for that header that is practically implementable on the real hardware is a very difficult problem, that is better left to the compiler, because to solve it one needs to know a whole bunch of details about how the ingress and eress fields are laid out and should be used. To provide an analogy, imagine a C program that uses structs with a lot of odd-sized bit fields and you need to DMA some of those fields to be picked up on the other side, while doing it in the most efficient way with minimal bit twiddling and as few WORDS transferred as possible.

We are looking at a number of options that would allow the compiler the necessary flexibility while keeping us safe and suggestions are more than welcome. 

As an exercise, you can look at switch.p4 and determine what constitutes bridged metadata without the help from a tool (currently it is the compiler). It is really difficult to do and can be an error-prone process even without trying to lay out that header.

**Comment by mbudiu-vmw** [comment]
What @vgurevich is implying is that the internal headers are different from standard headers: they only exist within the switch, so there is some freedom in how they are laid out. For example, they don't need to be packed.

There is a very simple solution to this problem: just add an annotation which indicates that a certain header type is internal:

```
@internal
header BridgedMetadata {
    ...
}
```

This will allow the compiler to much up with the actual layout of that header according to various constraints of the architecture. This annotation promises that this header will never be serialized outside of the PSA device.

An alternative solution is to expose a BM type variable for the bridged metadata, which is `out` in the ingres and `in` in egress. The user is free to keep this empty.

It is difficult to segregate bridged metadata in switch.p4 because it was written this way; but it is very difficult to segregate intrinsic metadata too. So there is nothing fundamentally difficult about this. I claim that in practice you want users to understand what metadata is bridged, because then they understand there is a cost to it. The current P4-14 model makes it look like bridged metadata is free, so it encourages people to splurge it.

**Comment by ChrisDodd** [comment]
Regardless, the user still needs to find all the metadata being bridged and arrange for copies into and out of the bridged data structure.  This is tricky and error prone and a lot of extra work for the programmer, but is an unavoidable effect of introducing the ingress parser/egress parser in the pipeline.  Which is why IMO it is a bad idea to require them -- most programs won't need the extra functionality.  If we have two switch packages in PSA, one with them and one without, simpler programs can use the one without and have the compiler create and bridge metadata for them, and only complex programs that need the extra functionality have to go to the extra work.

**Comment by mbudiu-vmw** [comment]
There is a way to have your cake and eat it too: you can expose TWO (or three) PSA architectures, each of which is a refinement of the other one. The bottom one has an extra parser/deparser, the middle one has explicit bridged metadata, and the top one just has one big metadat structure shared between ingress and egress. The compiler can actually translate between these three representation automatically. 

You start by providing the bottom one, because the compiler is simpler. Then you provide the middle one, after you have implemented the required compiler support. Finally, you provide the top one, once you have implemented the liveness analysis required. 

The benefit of this approach is that it gives users the degree of control they may require; if the compiler does not do a good job, they can always override it.

The downside is a more complex PSA model. But this is a way that PSA itself could evolve - by adding new top-level packages.

**Comment by jafingerhut** [comment]
So a couple of basic question about a compiler auto-detecting the fields that should be copied from ingress to egress:

(a) In P4_16, where all user-defined metadata is passed explicitly as 'inout' parameter to the Ingress and Egress control blocks, how precisely would it be determined that an ingress and egress field were "the same one", and thus eligible for automatic inclusion in the set of bridged metadata fields?  Would it be required to have the same 'hierarchical name', i.e. if it were user_meta.x.y.z on ingress, would it have to be the same name user_meta.x.y.z for egress, and the same type?

(b) Would a field only need to be referenced in the egress control block to cause it to be auto-copied, or should it only be copied if it is read in egress code before it is assigned a value in egress code?

If it only needs to be referenced, then that means there could be unnecessary copying of fields that are always assigned in egress code before it is ever used in egress code.

If only fields that are read before writing in egress are copied, then that cannot be determined perfectly via static analysis, true?  Because the contents of tables are not known to the compiler, perhaps among other reasons.  This is the same reason why compile-time warnings that a value is used before it is initialized can have false positives.  So is the determination of these bridged fields expected to have false positives like this (i.e. copying some fields unnecessarily), due to a conservative compile time analysis?

**Comment by ChrisDodd** [comment]
When there is no ingress deparser/egress parser, the user metadata struct (type M) is passed from ingress pipe to egress pipe (inout in both).  So implicitly the entire thing needs to be copied.  Now the compiler can optimize this by eliding any metadata that is not written in ingress, or is always written in egress before it is read, or not read in egress at all.

When there is an ingress deparser/egress parser, the user metadata is an out parameter to the egress parser, so does not get any data from the ingress pipe -- it is all zeros at that point and needs to be explicitly filled in by the egress parser.

**Comment by jafingerhut** [comment]
Would there be compiler-calculated bridged metadata for packets recirculated from egress back to ingress?

For resubmitted packets?

For cloned packets?

**Comment by mbudiu-vmw** [comment]
This is a property of the architecture. Today's compiler does not do any architecture-specific analysis; in particular, it does not do any liveness analysis between different controls. One would have to implement a specific analysis in a back-end which "knows" more about how PSA works.

**Comment by vgurevich** [comment]
@jafingerhut ,

Not sure if there will be any headers that the compiler will determine automatically, at least in the current vision of clone/resubmit/recirculate (if I understand it correctly).

The header(s), prepended to the clone packet (i.e. emitted by clone_out extern) is what will be passed with it. They can have the same properties as the header(s) for bridged metadata, i.e. flexible layout, decided by the compiler.

Same goes about the header(s) prepended to the resubmitted packe. The extern name will be different, though (resubmit_out?), but the idea is the same. BTW, remember that in the case of resubmit, these newly emitted headers will be prepended to the original bytestream (i.e. pre-parsed and not post-deparsed) version of the packet. So, very similar to clone-ingress-to-egress. 

For recirculated packets we will probably have to use "regular" headers, because they will have to be deparsed in the egress deparser together with the packet (i.e. they will be emitted into packet_out) and thus will have a good chance to appear on the wire.

**Comment by jafingerhut** [comment]
@vgurevich You say "The header(s), prepended to the clone packet (i.e. emitted by clone_out extern) is what will be passed with it. They can have the same properties as the header(s) for bridged metadata, i.e. flexible layout, decided by the compiler."

OK, again a basic misunderstanding on my part here, I think.  I thought the idea of clone.emit() was that the argument was a header, with bits sent out in the order defined by the header variable given as an argument, like packet_out.emit().  Then, wherever that packet was next processed, those bits would be the first ones parsed by the egress parser.

If I understand your intent correctly, you want clone.emit() to be a collection of metadata fields, and the compiler packs those bits in some implementation-specific format, and those are exactly the 'bridged metadata' for that clone?  i.e. you want manually-specified bridged metadata for cloned packets, but auto-determined-by-compiler bridged metadata for normal packets?

By the way, I am not trying to push this any particular way here -- I am just trying to keep up with the proposals being described.  It is no no way clear to me yet how it all comes together, so asking lots o' questions.

**Comment by vgurevich** [comment]
@jafingerhut , don't worry -- not everything is clear to me either :)

In terms of the header prepended to either the clone (to pass some extra info from the processing of the "clonee" into the clone), to the resubmitted packet or to a regular packet, it can be **either** a regular header or this *@internal* (using Mihai's terminology) or *@flexible_layout" header. The only difference is that in the case of a regular header, it is the programmer that determines the actual bit layout of the header (in addition to the list of fields) and in the case of an *@internal@ header, the programmer only determines the list of fields, whereas the compiler determines the layout. Since the header is not going to leave the chip, as long as the deparser and the parser are in agreement about the actual layout, I wouldn't care about what it is. That's exactly the same idea behind the bridged metadata header.

I would not call it bridged metadata, though (maybe "cloning metadata"), but in any case it is not going to be automatically determined by the compiler. It will be specified manually. 

And, as we discussed, in the new grand scheme with two parsers and two deparsers even the *real* bridge metadata (the one that needs to be carried from ingress to egress) is going to be specified manually.

**Comment by jafingerhut** [comment]
Closing this issue, since it should be resolved by the merging in of PR #494
