### ISSUE TITLE
[PSA] Broadcast operation in PRE

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#407]
I was wondering if there is a possibility of adding a broadcast operation in PRE. This would avoid the need for creating multicast group for a common use-case. I am sure this has been discussed earlier, but I couldn't find any mention in the forum. Are there any cons?
I am also assuming that it would make sense to invoke this operation only in the ingress pipeline.

**Comment by jnfoster** [comment]
Is this like OpenFlow's "ALL" or perhaps its "FLOOD" pseudo port?

-N

**Comment by samar-abdi** [comment]
Yes, like the Openflow ALL reserved port.

**Comment by vgurevich** [comment]
Actually, a **real** broadcast to **all** ports is a relatively rate operation on modern switches, due to the fact that people tend to virtualize their networks. 

For example, ethernet with broadcast MAC address (FF:FF:FF:FF:FF:FF) rarely go to all ports. Instead they are only flooded to ports that are members of the corresponding VLAN. The processing of IPv4 broadcast packets (255.255.255.255) is even more intricate. And I am not even bringing up any tunneling techniques. 

At the same time, creating a multicast group that contains all the ports on a given device, all associated with the same RID is a trivial operation. Note, by the way that even if added automatically, it has to be tied to the given P4 program and would be useful only for primitive L2 broadcast only.

Therefore, I would strongly recommend against adding an explicit broadcast operation in PSA.
