### ISSUE TITLE
P4_14 (v1.0.4): "-" in const_value vs "-" in un_op

### ISSUE THREAD

**Issue by kheradmand** [p4lang/p4-spec#408]
It seems that there is ambiguity in the grammar between "-" in const_value and "-" in un_op. e.g in - 5. Does this make difference in semantics? Because according to the spec 

> For positive values the inferred width is the smallest number of bits required to contain the value. For negative values the inferred width is one more than the smallest number of bits required to contain the positive value.

and

>   For expressions, the value with largest bit width is identified and all other
>    values are converted to this width according to their own signedness.
>    The expression is then evaluated

Does - 5 , if evaluated as - (5) , yield 3 bits or 4 bits?
How about 6 - 5, 3 bits or 4 bits? (or 1 bit?)
How about 5 - 6 ?

**Comment by jnfoster** [comment]
I'm afraid this is indeed ambiguous and implementations may vary.

As I'm sure you're aware, it makes a difference to the semantics -- e.g.,
other operations may overflow depending on the bit width.

Unfortunately repairing this seems pretty difficult. For example, action
data are untyped and so an implementation has to make a choice since there
are multiple ways you could do it. In addition, P4_16 now has precise
static types, so these issues are all resolved. I realize that's an
unsatisfactory answer -- consider it a lesson in language design about why
types and semantics matters.

> Does - 5 , if evaluated as - (5) , yields 3 bits or 4 bits?
>
How about 6 - 5, 3 bits or 4 bits? (or 1 bit?)
>
How about 5 - 6 ?
>
I think these would all be 3 bits.

**Comment by kheradmand** [comment]
Hi @jnfoster, thanks for the response. 
I did not quite get why repairing this would be difficult. Specially I did not understand the action data example (it isn't possible to use expressions as action data, is it?)
Wouldn't giving "-" in const_value higher priority than "-" in un_op solve the problem?
If not, do you think it would be a good idea to explicitly mention this problem in the errata appendix ?

**Comment by jnfoster** [comment]
It's just that action data are untyped, so their widths have to be inferred. I agree this is mostly unrelated to negating constants.

**Comment by jnfoster** [comment]
I would recommend following the papro
