### ISSUE TITLE
P4_14 (v1.0.4): lpm match

### ISSUE THREAD

**Issue by kheradmand** [p4lang/p4-spec#411]
The specification for lpm match says:

>  lpm: This is a special case of a ternary match. Each entry’s mask selects a prefix by having a divide between 1s in the high order bits and 0s in the low order bits. The number of 1 bits gives the length of the prefix which is used as the priority of the entry.

How is the priority decided in tables that match on more than one lpm fields?

**Comment by jafingerhut** [comment]
I don't know of anywhere in any P4 documentation that says this (perhaps it should somewhere), but  the only thing that makes sense to me is that a table can have at most one 'lpm' match_kind for at most field, and if it does, all other fields (if there are any) should be 'exact' match_kind.  Then the match behavior is well defined, I believe.

I believe that perhaps the open source p4c and/or behavioral-model might enforce that restriction.

**Comment by kheradmand** [comment]
Hi @jafingerhut, thanks for the response. I saw one example program [here](https://github.com/p4lang/p4c/blob/master/testdata/p4_14_samples/issue60.p4).
I think it is a good idea to add this limitation (at most one 'lpm' match) to the specification.

**Comment by jafingerhut** [comment]
I agree that adding this limitation to the spec would be reasonable.

Note that the example you point at was due to this issue #60 for the p4lang/p4c repository: https://github.com/p4lang/p4c/issues/60

A comment there mentions that an earlier P4 compiler rejects such a program with an error, specifically because it has 2 lpm fields in key of a table, and the current version of p4c-bm2-ss also rejects that program with an error because of the 2 lpm fields.  Some programs are in the test suite collection specifically to test that the compiler catches errors.
