### ISSUE TITLE
P4_14 (V1.0.4): push vs. add_header on arrays with non-contiguous valid elements

### ISSUE THREAD

**Issue by kheradmand** [p4lang/p4-spec#431]
I just wanted to make sure that my interpretation of the specifications of `add_header` and `push` primitive actions are correct:

The spec of `add_header` says:

> If header_instance is an element in a header stack, the effect is to push a new header into the stack at the indicated location. Any existing valid instances from the given index or higher are copied to the next higher index. The given instance is set to valid.

The spec of `push` says:

> Existing elements will be shifted by count: an element at index N will be moved to index N+count. count number of new elements will be pushed at indices 0 to count-1, zeroed out and set valid. This primitive leaves the array’s size constant; if an array is already full, elements pushed to indices beyond the static array size will be lost.

So if have the following array:
```
header_type ht{
  fields {
     f : 8;
  }
}

header ht a[5];
```
such that 
```
a[0].f = 1
a[1] is invalid
a[2].f = 2
a[3].f = 3
a[4] is invalid
```

The result of calling `add_header(a[0])` will be
```
a[0].f = 0
a[1].f = 1
a[2].f = 2
a[3].f = 2
a[4].f = 3
```

And the result of calling `push(a,1)` will be
```
a[0].f = 0
a[1].f = 1
a[2] is invalid
a[3].f = 2
a[4].f = 3
```

Is that correct?

**Comment by jnfoster** [comment]
I was not involved when this text was written, but this behavior is clearly non-sensical. I think the intention was probably that `add_header(a[0])` and `push(a,1)` are identical? So the phase "are copied" is not quite right. 

@chkim4142 do you know?

**Comment by jafingerhut** [comment]
I have written a test P4_14 program that exercises add_header() and remove_header() primitives on a header stack.  I have also auto-converted the P4_14 source to P4_16 using p4test, and a simple automated test that checks exactly how the latest open source p4lang/p4c and p4lang/behavioral-model (bmv2 using simple_switch executable) implement these 2 primitives.  The files are in this repository, if you are interested in the gory details: https://github.com/jafingerhut/VPP_P4  (program ipv4-hdr-stack.p4_14.p4, and test script ipv4-hdr-stack-tests.py).

The behavior I have observed is that add_header() on one element of a header stack makes that one array element valid (leaving it valid if it was already), and it _does not modify_ the validity bits of any other elements of the header stack.  There is no 'shifting' at all -- everything else remains exactly where it was in the header stack array.

The same is true for remove_header() on one element of a header stack -- no 'shifting' is performed.  The specified header stack element becomes invalid if it was valid, or remains invalid if it was invalid.

It appears that simple_switch allows 'holes' in the middle of a header stack, and emits them with no problem.  By 'holes', I mean an invalid header with valid headers earlier and later in the stack.  By emitting them with no problem, I mean that packet_out.emit(header_stack_name) appears to operate by iterating through all elements of the header stack from 0 up to the maximum index, and independently checking for each one whether it is valid, and if so, copying data to the output packet.  It does not stop when it first reaches an invalid header, but keeps going.

The auto-converted P4_16 program has the same behavior for the translated <header_stack_element>.setValid() and <header_stack_element>.setInvalid() method calls.

See this related issue raised earlier: https://github.com/p4lang/p4-spec/issues/284

If all of the simple_switch behavior described above is the expected behavior, then perhaps the P4_14 spec should be updated to match it?

**Comment by jafingerhut** [comment]
I've written probably way too many words on the details of header stack operations, and how they differ between the P4_14 v1.0.4 spec, P4_16 v1.0.0 spec, and the current implementation in simple_switch in p4lang/behavioral-model.

Here are the results so far.  I may tweak it to add a few more details soon, but I doubt I'll spend much more time on it: https://github.com/jafingerhut/p4-guide/blob/master/README-header-stacks.md
