### ISSUE TITLE
Liveness of action profile members

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#457]
A common action_selector use-case is to determine next hop port. If the port is down, we do not want the dataplane to send traffic to it. In other words, if the action of an action_selector member to set egress port, then it would be useful to "deactivate" that member from all groups programmed to the selector, without involving the controller. The P4Runtime API has a "watch" field associated with members that attempts to capture the liveness of the member based on liveness of a set of ports.

There is no change in the action selector constructor in the PSA, but this behavior will need to be captured in the PSA documentation and all PSA targets will need to implement member liveness.

**Comment by vgurevich** [comment]
@samar-abdi ,

This is, indeed, a fairly common use-case, but we need to have a generic mechanism, since action_selectors can be used for a variety of other things and setting the port can also happen totally outside of an action_selector. Therefore, tying them together is not a very good idea, in my opinion.  

I suggest we split the problem into the following smaller ones:

1. We need to decide what's the mechanism an external entity can notify the data plane of some event (such as port down). 
2. How this notification can change the state of the data plane
3. What specific state should be changed to indicate the port going up or down
4. How the rest of the data plane algorithm can consume that state (in other words what reactions will be available)

I do not have a lot of answers yet, but I I think that using the list above will allow us to develop a more generic and logical solution.
