### ISSUE TITLE
PSA Document interaction between direct counters/meters and action profile/selector

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#466]
Do we allow a table with an action profile or selector to have direct counters and/or meters?

If so, how many direct counters does a table using an action profile have?  That is, what is each counter value associated with in a 1-to-1 relationship (if the table has no action profile or action selector, the 1-to-1 relationship is between counter values and table entries.)

When an action is executed that updates a direct counter for a table using an action profile, which counter does it update?

Same questions as above, but for tables using an action selector.

**Comment by jafingerhut** [comment]
@samar-abdi @vgurevich Just calling out your names to draw your attention to this issue.  I worry that there are differences in how people implement action profiles and action selectors that the current most accurate answer is "it depends on how you implement action profiles and action selectors in your target".

**Comment by vgurevich** [comment]
@jafingerhut ,

The question you pose in the second paragraph is the most important one: do direct counters/meters correspond 1-1 to match entries (represented by the table itself) or 1-1 to the action entries? In tables without action profiles, there is a 1-1 correspondence between match and action entries, so that's no problem, but in tables with action profiles there is many-to-1 relationship instead.

Given that incrementing the counter or executing a meter is clearly an action, I'd say that most probably direct counters/meters should have 1-1 correspondence to the action entries and therefore, if a table has an action profile, then they should become additional attributes (constructor arguments) to this action profile. However, I can also see an argument of treating these resources separately, like an additional specialized action, associated 1-1 with a match entry. In that case, they should remain table properties.

Personally, I feel that unless we can make a very clear choice between these two designs, it might be prudent to table this issue and simply do not allow mixing action profiles (that already are almost at the boundary of permissible in my opinion) and direct resources. We can always allow them later should the need arise.

**Comment by samar-abdi** [comment]
A direct counter needs to be explicitly incremented and a direct meter explicitly read from inside the action body. There is no implicit modification of direct counter or execution of direct meter. At least that is how these resources are implemented in v1model. As for the addressing of the direct meter or counter, it is the match key of the table that instantiates them. 

Here is an example:

table foo {
  key = {
    h.f1 : lpm;
    h.f2 : selector;
  }
  actions  = {a; b;}
  counters = c;
  implementation = as;
}

action a(in PortId_t p) {
  ostd.egress_port = p;
  ostd.drop = false;
  c.count();
}

action b() {
  ostd.drop = true;
}

action_selector(HashAlgorithm.crc16, 1024, 10) as;

------------
In the example, if an entry in table `foo` is hit, the corresponding direct counter cell of `c` will only be incremented if the member or group pointed to by the entry has action `a`.

So, to further @vgurevich point, if an action executed on hitting a table entry would never touch the direct counter or meter, the resource is not really needed as part of the entry.

This might be a design decision left to the P4 programmer. Direct resources have the convenience of not needing explicit indexing from the action. But, if the resources are being unused in most entries, it might be better to make them indirect.

**Comment by samar-abdi** [comment]
BTW @jafingerhut thanks for bringing this up. I think member stats in action selectors is not convenient with what we have in PSA today. The controller can aggregate counter data from table entries to get member stats for action profiles and group stats for action selectors. However, since the member selection within a group in an action selector is dynamic, there is no easy way to tally the number of times a member was hit using direct counters.

I think it is fair to note this in PSA and leave it as possible future improvement.

**Comment by cc10512** [comment]
Since action profiles are table implementations, I don't think it makes sense to associate them with match entries. Therefore I agree with the points raised by both @vgurevich and @samar-abdi that we need to think a bit more about these and discuss it in one of our subsequent meetings.

**Comment by samar-abdi** [comment]
One option might be to have two different action profile/selector types; the type can be passed as a constructor argument.
1. No counting or metering - current implementation
2. With group/member counting - The API (P4Runtime) can modify/query the group and member counter by providing the handle to the group/member object.
3. With group/member metering - The API (P4Runtime) can modify/query the group and member meter by providing the handle to the group/member object.
4. With group/member counting and metering - The API (P4Runtime) can modify/query the group and member counter or meter by providing the handle to the group/member object.

The current usage of counter attribute in tables can stay the same. i.e. the counter/meter is indexed by the match key and is associated with the table entry.

The only inconsistency I see here with respect to direct counters/meters in direct tables is that the counting/metering of groups and members will be implicit. In counters/meters associated with tables, the increment counter/execute meter action is explicitly called in the action.

IMHO, I do not see why all counting/metering of direct resources cannot be implicit. Why would one have a direct counter if there is no intent to increment on a hit?

**Comment by jafingerhut** [comment]
@samar-abdi Regarding this question: "I do not see why all counting/metering of direct resources cannot be implicit. Why would one have a direct counter if there is no intent to increment on a hit?"

I believe one use case I have heard for this is to have some actions that do counting, and other similar ones that do not, making it easy for the control plane to disable counting for a time, without changing the P4 program, merely by changing actions used in table entries.

Exactly why it is considered a benefit to disable/re-enable counting isn't complete clear to me, unless there is some kind of extra work placed on the software to background read&clear counter values from a hardware implementation when counters are enabled, that can be saved when counters are disabled.  Implementations I am familiar with would budget for this background software work all of the time, regardless of whether counters were being updated in the fast path or not.

**Comment by jafingerhut** [comment]
Discussion in 2017-Dec-20 P4 architcture working group was that PSA implementations need not support direct meters or direct counters on the same table that uses an action profile or action selector.  Documented this with this PR: https://github.com/p4lang/p4-spec/pull/540

Also documented that a PSA implementation must support both a direct meter and a direct counter on the same table.

That PR does not say anything about how many direct meters should be supported on the same table, or how many direct counters on the same table.  At least one is probably good enough for almost all use cases.

**Comment by samar-abdi** [comment]
P4Runtime assumes at most 1 direct counter and at most 1 direct meter in a table. I am assuming that the bar for PSA is 1 meter + 1 counter per table as long as it is not an indirect table. We don't have to make that restriction in PSA, but similar to metadata field bitwidths, we can say that at most 1 is accessible by P4Runtime.

On a separate note, are there use cases of multiple direct counters for a table?

**Comment by jafingerhut** [comment]
I don't know of any use cases.  If we are all comfortable limiting PSA to at most one direct meter per table, and at most one direct counter per table, for the lifetime of PSA, we could simplify the syntax a bit to eliminate the list with curly braces { }.

**Comment by samar-abdi** [comment]
I would be in favor of limiting PSA to at most one direct meter and one direct counter. I can't think of a single reason to have more and it would make things easier on the API side.
