### ISSUE TITLE
PSA How many direct counters/meters can be associated with the same table?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#479]
Should the PSA spec say that PSA implementations should support up to 1 direct counter per table, but it need not support more than 1 direct counter for the same table?  Is there any known desire for more than one direct counter on the same table?

Same question for direct meters.

Should it be allowed to have a table with a direct counter and a direct meter?

**Comment by vgurevich** [comment]
@jafingerhut ,

Do we allow multiple table properties with the same name? If not, then it will not even be possible to specify more than 1 direct counter/meter for the table, since we use a well-defined property name here. Also, it doesn't make a lot of sense (at least for the counters): why would you have two counters counting the same thing? There is a good use case for multiple meters, but, again, the way we specify them won't allow more than one anyway.

Mandating one (which is essentially the same as mandating the support for the property) seems reasonable. Having both in the same table is sensible too -- we can mandate that as well.

**Comment by jafingerhut** [comment]
The syntax proposed for them in the PSA allows a list of them, precisely to allow the syntax to specify more than one, if it is useful.  See the lines of code that have been part of the PSA draft for several months now:

https://github.com/p4lang/p4-spec/blob/master/p4-16/psa/examples/psa-example-counters.p4#L138-L141

**Comment by vgurevich** [comment]
@jafingerhut,

Oh, I see... Well, I guess your proposal still stands: mandate one, allow more than one.

Should we consider creating another table, detailing all architecture-specific table properties, such as
* property name
* syntax
* acceptable values (especially if those are externs)

**Comment by jafingerhut** [comment]
PR for adding a table of P4 table properties added by PSA: https://github.com/p4lang/p4-spec/pull/481

**Comment by cc10512** [comment]
Fixed by #540.
