### ISSUE TITLE
Consistent naming conventions (attempt number 2)

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#483]
This is a follow-up to the case #315 .

We started to use psa_ prefix, but not consistently.  For example, we do not use it for externs.

I suggest we have a discussion (that I think we wanted to have, but haven't really had) and perform  wholesale renaming/cleanup before  releasing the draft.

**Comment by jafingerhut** [comment]
@cc10512 Calin can comment here, but we were hoping to release a _draft_ before the Fall developer day on 2017-Nov-10, nominally scheduled for today (2017-Nov-08).  I am doubtful we can have a fruitful discussion on names, and all the renaming done, before 2 days from now.  I don't know how desirable it is to wait a couple more weeks to release a draft for this purpose.

**Comment by cc10512** [comment]
The Naming conventions section clearly specifies the naming. I don't think we should name externs prefixed with psa_. For comparison, the functions in the c (or glibc) library are not prefixed with glibc. I see the externs at the same level, especially because quite a few of our externs define wide-spread functionality.

As discussed on the PR, it would be more appropriate to use namespaces. When the language supports them, we shall namespace the externs.

**Comment by cc10512** [comment]
The Naming conventions section clearly specifies the naming. I don't think we should name externs prefixed with psa_. For comparison, the functions in the c (or glibc) library are not prefixed with glibc. I see the externs at the same level, especially because quite a few of our externs define wide-spread functionality.

As discussed on the PR, it would be more appropriate to use namespaces. When the language supports them, we shall namespace the externs.

**Comment by cc10512** [comment]
The Naming conventions section clearly specifies the naming. I don't think we should name externs prefixed with psa_. For comparison, the functions in the c (or glibc) library are not prefixed with glibc. I see the externs at the same level, especially because quite a few of our externs define wide-spread functionality.

As discussed on the PR, it would be more appropriate to use namespaces. When the language supports them, we shall namespace the externs.

**Comment by cc10512** [comment]
The Naming conventions section clearly specifies the naming. I don't think we should name externs prefixed with psa_. For comparison, the functions in the c (or glibc) library are not prefixed with glibc. I see the externs at the same level, especially because quite a few of our externs define wide-spread functionality.

As discussed on the PR, it would be more appropriate to use namespaces. When the language supports them, we shall namespace the externs.

**Comment by vgurevich** [comment]
@jafingerhut , @cc10512 
As long as we believe that it is OK to release a *draft* and rename later, that's fine. If, however, we would be hesitant to make that kind of changes "because the draft has been published" then I'd rather do it now or figure out something else. Perhaps, we need to make sure we put the necessary wording that anything is still subject to change.
