### ISSUE TITLE
PSA: Passing parser error to controls

### ISSUE THREAD

**Issue by cc10512** [p4lang/p4-spec#489]
Follow up from the discussion https://github.com/p4lang/p4-spec/issues/339#issuecomment-323568991

**Comment by jafingerhut** [comment]
@cc10512 I don't see anything in the comment you link to that isn't already in the PSA, so please call out specifically what you think needs to be addressed in the document.  For example, here are some points mentioned in that comment that are already documented, and where in the PSA they are:

For passing parser error state from parser to controls, there is an explicit output metadata field from the parsers, and an explicit input metadata field into the Ingress and Egress control blocks containing that error code, documented in Section 6.1 for ingress, and 6.4 for egress.

There is a sample program in Section 7.5.3 "InternetChecksum examples" that shows one way to check whether an error occurred during ingress parsing during the Ingress control block, drop the packet if an error occurred, and maintain a per-error packet count.

There is only a single parser_error field passed into Ingress and Egress, not more than one.  I don't know what multiple-error status case @vgurevich may have had in mind in his comment.

The parser_error_location metadata field that was once in the PSA document has been removed.

**Comment by vgurevich** [comment]
@jafingerhut ,

Now with checksum verification moved into the parser, I think this is much less of an issue (if at all).

**Comment by cc10512** [comment]
@jafingerhut you are right, of course. I missed the example of handling errors in InternetChecksum.

We have throughout the document the following sentences: 
>A comment saying “recommended to log error” is not a requirement, but a recommendation, that a PSA implementation should maintain a counter that counts the number of times this error occurs.

These apply to parser errors and other controls. I propose that we should have a standalone (sub)section that deals with error handling, in which we also show the example of parse errors. If you think that's valuable, I will create a PR. Otherwise, we can close the issue.

**Comment by jafingerhut** [comment]
Yes, there are several places that mention "recommended to log error when <some condition happens>".  None of them are for the parser detecting the errors mentioned in the P4_16 spec.  I had been assuming that since they are part of the P4_16 spec, they are required for a PSA implementation, too.

A standalone section for dealing with errors seems like a reasonable idea to me.  The InternetChecksum example of dropping a packet that has a checksum error could be moved to a new section dedicated to that purpose.  Another example I would like to see there is a way to clone a packet with a parser error to the control CPU, without modification, but perhaps with some extra header added to the beginning indicating what kind of error was found.

**Comment by jafingerhut** [comment]
Note: An example program that clones a packet with a parser error to the control CPU (mentioned near end of previous comment) was added with this PR: https://github.com/p4lang/p4-spec/pull/541

**Comment by milad14000** [comment]
@jafingerhut In your example you're matching on ```parser_error``` which has a type ```error```. I'm curious whether it's allowed to match on keys with type ```error``` or ```enum``` in p4_16 as it's stated in 8.3 of the spec: "Similar to errors, enum expressions only support equality (==) and inequality (!=) comparisons. Expressions whose type is an enum cannot be cast to or from any other type."

Also, it's not clear to me how you'd populate the table from control plane as the numeric values are compiler-generated and not known to the programmer.

**Comment by mbudiu-vmw** [comment]
Exact matching only requires equality testing.
The control-plane issue is separate.
Our compiler has a pass which converts enums to bitstrings. Currently the programmer cannot influence how this is done, it's a property of the back-end.

**Comment by antoninbas** [comment]
@milad14000 we could include a mapping from enum name to compiler-allocated value in the P4Info message, just like it is done in the bmv2 JSON today (https://github.com/p4lang/behavioral-model/blob/master/docs/JSON_format.md#errors).

However, for portability of the P4Info, it would require the compiler-allocated values to be the same for all backends and they would need to be allocated before P4Info is generated (so in the frontend?).

**Comment by mbudiu-vmw** [comment]
There is a discussion in the p4 spec group about "serializable" types. The solution would require a way to specify how a type like an error or enum is written on the wire when talking to an external entity. A possibility is an annotation:

```
@serialize(32)
enum X { ... }
```

This meaning that you convert an enum to a 32-bit integer. (You can't write `@serialize(bit<32>)` unfortunately.). Then the conversion is portable.  Alternatively, if the language mandates a conversion algorithm the rules can be hardwired and we could put this in the front-end.

**Comment by jafingerhut** [comment]
@milad14000 There _should_ be a way to maintain counters on a per-error basis, or per-enum basis.  Whether production code ends up using the approach in that example program, or something else, remains to be seen.

One way is making sure a device-independent controller can use enum names/portable-values to configure different devices that use custom enum values inside their data plane, probably converting names/portable-values to custom-values in the local agent software.

Another is to define for such types a numeric value, which is a proposal before the P4_16 language working group to be discussed.

Maybe even both of those things may be possible in the future, or some 3rd way I'm not thinking of right now.  I'm confident that P4-knowledgeable people are interested enough in the problem that at least one workable way will proceed forward.

**Comment by jafingerhut** [comment]
Regarding the issue of enabling tables to contain key fields of type error (and a few others), this issue is open for p4c to add that support: https://github.com/p4lang/p4c/issues/1067

There has been work in the P4 language working group adding support for enum types with a 'backing type', which effectively makes such enum types much more like values of type `bit<W>`, with straightforward casting between the enum and `bit<W>` values.  That enhancement did not address values of type `error`, but I think if that is desired a separate issue besides this one should be created specifically for that.

I am closing this issue, but creating another one for future consideration, based on a comment early in this issue by Calin suggesting a dedicated error-handling section in the PSA spec.
