### ISSUE TITLE
PSA_SWITCH macro not standard P4-16

### ISSUE THREAD

**Issue by jamescoole-cisco** [p4lang/p4-spec#495]
The package instantiation helper macro in [psa.p4](https://github.com/p4lang/p4-spec/blob/e3edd48104f66fcd4512ad43056df297c66726e3/p4-16/psa/psa.p4#L645):

```
#define PSA_SWITCH(ip, ep) PSA_Switch(                           \
                                      (ip),                      \
                                      PacketReplicationEngine(), \
                                      (ep),                      \
                                      BufferingQueueingEngine())
```

takes arguments, which makes use of preprocessor functionality that isn't currently required by [P4-16](https://github.com/p4lang/p4-spec/blob/e3edd48104f66fcd4512ad43056df297c66726e3/p4-16/spec/P4-16-spec.mdk#L1144).

**Comment by jafingerhut** [comment]
Good point.

I know that Calin @cc10512 is hoping that we find a way that when you write a PSA P4 program, you can #include "psa.p4", then never have to mention PacketReplicationEngine or BufferingQueueingEngine in your P4 program at all, since they have no methods to call from P4.  The only motivation to keep them is so they have an instance name that the control plane API can know and use for configuring the PRE (e.g. for multicast group membership add/remove).

I have a feeling this question has been answered before, but is a P4_16 architecture allowed to simply say "these externs come pre-instantiated with these instance names?"

Maybe just having these lines in psa.p4 would do it?

```
PacketReplicationEngine() pre;
BufferingQueueingEngine() bqe;
```
I guess then we would still want to say that it is an error to construct additional instances of those externs.

**Comment by hanw** [comment]
Or, we can wait for named argument to support the following
```
package PSA_Switch<IH, IM, EH, EM> (
   IngressPipeline<IH, IM> ingress,
   PacketReplicationEngine pre = PacketReplicationEngine(),
   EgressPipeline<EH, EM> egress,
   BufferingQueueingEngine bqe = BufferingQueueingEngine());
```

**Comment by jafingerhut** [comment]
Elimination of the PSA_SWITCH preprocessor macro should be removed soon with this PR: https://github.com/p4lang/p4-spec/pull/612

Discussion of optional/named parameters is ongoing in the language design working group.  We shouldn't wait for that to happen to resolve this issue -- merging the PR above should do it.

**Comment by jafingerhut** [comment]
Closing this issue now that P$ #612 has been merged.
