### ISSUE TITLE
P4 2016 draft: named field lists

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4-spec#51]
The p4-16 language does not have anything equivalent to named field lists.

**Comment by jafingerhut** [comment]
I believe that the PSA draft we have now has an alternate method for specifying metadata that gets carried with packets, both for cloned packets and all others that can carry metadata "next to" each packet.

I know that Vladimir has mentioned field lists, which have properties that they are like references to locations, rather than the current values of the fields at the point of the field list definition, might be useful in defining language features such as the one proposed in the issue linked below, but it isn't clear to me yet why field lists help there.

https://github.com/p4lang/p4-spec/issues/516

**Comment by jnfoster** [comment]
Discussed at 11/5/2018 LDWG. Still in hibernation.

**Comment by jnfoster** [comment]
@mbudiu-vmw should this issue be closed if we take the `clone3_with_field_lists` proposal?
