### ISSUE TITLE
P4_16 Change status of 'size' table property to 'reserved' (or similar) in spec

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#514]
There has been some discussion in the P4 Arch WG about names of table properties, and so far all new table properties defined in the PSA specification have a prefix of 'psa_' in hopes of avoiding name collisions there.

There was some discussion of whether 'psa_size' should be created, but given the prevalence of using the table property 'size' for this purpose, even though it currently doesn't seem to be a required table property recognized by P4_16 implementations, it was discussed that perhaps size could be mentioned as some kind of a 'reserved' table property name in P4_16.  The goal is to warn people against defining that table property name for any purpose other than specifying a desired minimum number of table entries that the implementation should support for that table.  The type of value (compile time constant integer) and units (number of entries) would probably be included in that as well.

Reference: https://github.com/p4lang/p4-spec/pull/481

**Comment by mbudiu-vmw** [comment]
I don't understand why not having the size being reserved in the P4-16 spec prevents PSA using this name.
In general, if you won't be using PSA.p4 then you should not expect inter-operability, so if some other back-end uses the size property for some other purpose than PSA does, it won't really make a difference.

**Comment by vgurevich** [comment]
@mbudiu-bfn,

While it is fairly clear that P4 code is not generally portable across architectures, it would be nice to minimize porting pain and this means that things like externs, type and table attributes should either have architecture-specific names or have the same semantics across the architectures. 

Otherwise, it will be really difficult for people, working with different architectures to exchange or even discuss each other's code.

**Comment by jnfoster** [comment]
Speaking for myself, `size`, `default_action`, and `entries` all seem like good candidates to be elevated to reserved properties in the spec.

**Comment by cc10512** [comment]
I would add `implementation` to @jnfoster's list. Again, a fairly generic term that is likely to span a number of architectures.

**Comment by jafingerhut** [comment]
@jnfoster Maybe I am missing something, but v1.0.0 of the P4_16 language spec seems to require all of: key, actions, default_action, and entries.  Each has their own subsection in the spec describing them, and the types of value that may be given to them.

size and implementation are mentioned in examples, but don't have their own subsections specifying what values they can take.

**Comment by mbudiu-vmw** [comment]
@jafingerhut is right. The first four are part of the official spec.
The reason that size and implementation aren't is because their semantics is not clear.
As an example, the ebpf back-end uses just implementation to specify both.
Some other back-ends may need neither.
The  fact that they are recommended in the spec (as examples) will probably be enough for people to use these names anyway. I don't know if we have to mandate them. This will be true even more after PSA is published, because I expect most other architectures that will follow will start by copy-and-paste from PSA.

**Comment by jafingerhut** [comment]
@mbudiu-vmw Right now the PSA spec says nothing about any kind of table property related to size, and there are no plans that I am aware of to add such a thing.

It would certainly be possible to add a size-related table property to the PSA spec, but the existence of 'size' as an integer value in the open source P4 tools, and I suspect at least some commercial products, leads us to be cautious about defining things in a way that conflicts with existing use.

**Comment by mbudiu-vmw** [comment]
If you can't add it to the PSA spec then you can't add it to the P4 spec; whatever reasons you give will apply there as well.

**Comment by jafingerhut** [comment]
This PR proposes adding size as a standard optional table property to the P4_16 language spec: https://github.com/p4lang/p4-spec/pull/603

**Comment by jafingerhut** [comment]
PR #603 was merged after approval, so closing this issue.
