### ISSUE TITLE
[PSA] Capping the bitwidth of PSA core types to 64

### ISSUE THREAD

**Issue by samar-abdi** [p4lang/p4-spec#518]
The bitwidth of PSA core types is currently unspecified. This is because different HW may have different port bitwidth etc. However, can we agree on capping this number to 64 so that we can safely use uint64 for the metadata fields in the API?

**Comment by jafingerhut** [comment]
We can bring this up at the next PSA meeting to be sure, but I would be very surprised if any PSA implementation would voluntarily choose a width larger than 64 bits for any of the types defined in psa.p4 as 'bit<unspecified>'.  Having an explicit statement in the PSA that for types X, Y, Z, etc. that the P4 Runtime API only supports up to 64 bits for each of those types, thus an implementation would potentially be throwing away bits if they made it wider than that, seems reasonable.

**Comment by cc10512** [comment]
Are you sure? What if you want to represent a copy of an ipv6 address as metadata? Don't you need 128 bits?

**Comment by antoninbas** [comment]
I think we are only targeting the so-called `PSA_CORE_TYPES` (https://github.com/p4lang/p4-spec/blob/master/p4-16/psa/psa.p4#L50) which are used for PSA metadata fields. This does not apply to user-defined metadata fields.
The PSA metadata fields obviously have a special status because they are a property of the architecture and are referred by name in the P4 Runtime API (e.g. the multicast group id). It is much easier to manipulate them in software if they fit in a 64-bit integer. All user-define fields (protocol or metadata) remain arbitrary bitstrings.

**Comment by cc10512** [comment]
If that's the case, it seems reasonable.

**Comment by samar-abdi** [comment]
@cc10512 
Yes, this is only for the core types that appear in the standard input/output metadata. Specifically, we want the PRE P4Runtime to use uint64 for ports, clone session ids, class of service, multicast group ids and egress instance

**Comment by jafingerhut** [comment]
Closing this issue, resolved by this PR: https://github.com/p4lang/p4-spec/pull/539
