### ISSUE TITLE
Support table entry timeout in PSA?

### ISSUE THREAD

**Issue by hanw** [p4lang/p4-spec#523]
There is currently no specification about the table entry timeout behavior in PSA. We probably need an `idle_timeout` extern to implement the idle and hard timeout features in OpenFlow.

**Comment by jafingerhut** [comment]
As far as _implementation_ of this goes, I think we are talking about a feature that is likely to be implemented in device-specific driver/agent software that is near the device, yes?  Given the discussion around watch ports for action selectors, wanted to make sure this is similar in kind to that as far as expectations of how it is implemented.

**Comment by cc10512** [comment]
Discussion in P4Runtime WG: https://github.com/p4lang/PI/issues/265

**Comment by antoninbas** [comment]
Not sure if it's appropriate to close this. It looks like there is going to be a `psa_` table property to enable idle timeout in a table.

**Comment by jafingerhut** [comment]
As far as the data plane portion of this feature goes, it seems like at the very minimum, a 1-bit flag per table entry is needed on a table that wants to support this feature, which would need to be assigned a value of 1 whenever the entry was matched, and some background task would periodically read-and-clear it to see which ones had not been matched in the last period of time.  That would probably only support a fairly coarse specification for timeout, e.g. on the order of 100s of millisec or longer.

There is an engineering tradeoff between number of bits per table entry devoted for a feature like this, and the precision in the timeout value that can be achieved.  i.e. if you wanted a timeout per entry that times out if an entry has not been matched for 7 seconds, but it should never time out for at least 6 seconds, then you need at least 3 bits per table entry, representing number of seconds since the entry last matched (rounded down to the next whole second).

Do we expect this to be a requirement for PSA devices, or a recommended feature?

**Comment by jafingerhut** [comment]
Closing this issue in favor of the duplicate issue https://github.com/p4lang/p4-spec/issues/617 which I hope may get into PSA version 1.1.
