### ISSUE TITLE
P4_16 operator precedence

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4-spec#551]
See https://github.com/p4lang/p4c/pull/1134

**Comment by ChrisDodd** [comment]
(copying my comments/description from the PR)

Despite the fact that the P4_14 spec says that expressions have "syntax, semantics, precedence, and associativity matching that of C" (p7 end of section 1.5.1), if you look closely at the grammar in the spec, you find that the precedence of bitwise operators (&, |, and ^) has been swapped with that of relations (==, !=, <, <=, >, >=). 

The P4_16 grammar is copied from a C grammar and has the same precedence as C. This difference between the P4_14 and P4_16 specs means that code like:

    if (hdr.field & 0xf == 1) {

has different semantics in P4_14 and P4_16. It's not a huge problem, as P4_16 will give you a type error for the above; you need to add parentheses to make it equivalent to the P4_14 code and fix the type error.

Arguably, the precedence in C is a mistake -- a historical accident due to the language originally conflating bitwise and logical operations.

The question is, what should we do? Are we fine with it being the same as C and different to P4_14, or would we prefer to "fix" the C precedence "bug" and go with the P4_14 precedence? Because of P4_16's strict typing and lack of implicit conversion between bool and bit values, this will always only manifest as a compile-time error and not ruintime unexpected behavior, regardless of which way we go.

**Comment by jnfoster** [comment]
Can we close this? Or do we need to discuss again on 2/12?

**Comment by ChrisDodd** [comment]
I still need to merge the p4c fix (which requires getting the corrected expected outputs), but other than that I think this can be closed.

**Comment by jnfoster** [comment]
Great!
