### ISSUE TITLE
PSA Can ActionSelector tables directly 'point to' actions, or not?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#576]
In the ActionSelector section, early on it says this in the latest PSA draft:

"A table with an action selector implementation consists of entries that
point to either an action profile member reference or an action profile group
reference."

If I understand the meaning of that correctly, when adding an entry to a table with an ActionSelector implementation, one can specify match criteria for the key fields (all but the 'selector' ones, at least), and then an arbitrary action and action parameters, with no mention of a group id at all?  Just like you can in a table without an ActionSelector implementation?

If that isn't what the sentence above means, I would appreciate clarification.

If it _does_ mean that, then the following sentence later in the same section seems to contradict it:

"Directly specifying the action as part of the table entry is not
allowed for tables with an action selector implementation."

**Comment by jafingerhut** [comment]
@samar-abdi Appreciate any answers you might have here on the intended meanings.

**Comment by antoninbas** [comment]
I'm not sure why you would interpret it like this. It doesn't make mention of direct actions at all. According to Samar's sentence, a match-entry of a table with an action selecor can either point to a member or a group, but in both cases there is indirection. On the other hand, if a table has an action profile (no selector) a match entry can only point to a member (and not a group) as per this sentence:
```
A table with an action profile implementation has entries that point to a member reference instead of directly defining an action specification.
```
Maybe it's the omission of "instead of directly defining an action specification" in the action selector case that you find confusing but IMO the last sentence that you quote makes it really clear.

**Comment by jafingerhut** [comment]
So there is a P4 Runtime API to create a member of a group in an action selector, and then add a table entry that says "matching key X should cause member Y to run", with no mention of a group id, and no mention of the action name or parameters?   (the action name and parameters would have been given earlier in a separate control plane operation that created member Y?)

If so, then it makes more sense than my initial reading.

Is the best reference for ActionProfile and ActionSelector control plane operations the P4 Runtime API proto file?

**Comment by samar-abdi** [comment]
Hi Andy, A table entry can point to a member (which may or may not be a part of a group). And of course, the table entry can point to a group. P4Runtime makes it pretty explicit by allowing a oneof of direct action, action profile member or action profile group in the TableAction.

**Comment by jafingerhut** [comment]
Closing this, as I believe all of my questions were answered.
