### ISSUE TITLE
Ethernet frame payload padding and P4

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#587]
This is probably just a minor nit that isn't worth worrying much over, but I will ask anyway.

Ethernet frames have a minimum length of 64 bytes.  14 bytes of header + 46 or more bytes of Ethernet frame payload (possibly beginning with an Ethernet 802.1Q, IP header, etc.), + 4 bytes of frame CRC.

IPv4 packets can be as small as 20 bytes.  TCP ACK packets, a very common packet, are 40 bytes long if there are no IPv4 or TCP options (20 IPv4 + 20 TCP).

When a P4 device with Ethernet ports receives a minimum-sized frame, can this happen?

parser parses Ethernet header + 20-byte IPv4 header + 20-byte TCP header.  The 6 'padding' bytes inside the Ethernet frame are received by the parser as part of the packet (but not the 4 byte frame CRC), and the parser considers them 'the payload' for this packet, i.e. everything after the headers that were parsed.

ingress processing, egress processing, etc., whatever happens.

The deparser is reached, and let us say it prepends a new 20-byte IPv4 outer header after the received Ethernet header, just before the original IPv4 header and then also emits the same size headers that were received.  Because it is a P4 deparser, it also appends whatever the parser did not parse as payload, so those 6 padding bytes.  The resulting Ethernet frame out of the deparser is now:

14-byte Ethernet header + new 20-byte IPv4 header + original 20-byte IPv4 header + original TCP header + unparsed 6 bytes of payload

Then the Ethernet MAC for the output port receives that, calculates a correct 4-byte frame CRC, and sends it out, with the 6 bytes of padding there at the end.  It is there, although it is no longer necessary to make the Ethernet frame achieve a minimum size of 64 bytes.  It is just garbage carried along.

I don't know off hand the relevant standards here, but I suspect that most devices will carry that 6 bytes of padding along if they are L2-only devices, but if they are L3 devices, at least some will use the outer IP header total length field and only send out that much data, trimming off that extra unnecessary padding.  I wouldn't be surprised if some L3 devices would keep it.  Hopefully few or none would treat the packet as erroneous.

Anyway, just wondering if anyone had considered this scenario, and found it to be anything other than a weird nit.

**Comment by vgurevich** [comment]
@jafingerhut ,

Generally speaking, all these issues are mostly being dealt with by the MAC. MAC would be the component rejecting short ethernet frames at the ingress and MAC would be the component padding them at the egress. 

As we state in the beginning of P4 spec, it does not address the questions of how the packets get in and out of the switch and in what form. 

Unless you want to mandate that PSA devices must support Ethernet and then further mandate the functionality of the fixed-function MAC component (which we can, but I'd rather not), I'd stay clear out of these matters :)

**Comment by ChrisDodd** [comment]
It is a messy problem though -- perhaps there should be a way for a P$ program to specify the payload length (without parsing the entire payload), such that any padding after the payload can be cleaned up if not needed?  P4 similarly has no support for protocols with trailers instead of (or in addition to) headers -- I have no good ideas for how that might be added.

**Comment by jafingerhut** [comment]
@vgurevich My example is _not_ one the MAC should reject.  It is a packet that switch ASICs see in a large percentage of their input packets: IPv4 TCP ACK packet with no options.

If this extra unnecessary 'garbage' ends up getting preserved in some packets, and if it is harmless to downstream devices, I don't think this is a big deal.  If it is _not_ harmless, then this is an issue that should perhaps be thought about more.

**Comment by jafingerhut** [comment]
@ChrisDodd Agreed that if this issue is potentially harmful to the way downstream devices treat a packet that is sent by a P4-programmable device with Ethernet ports, then probably the simplest way to avoid it is to have a way for the P4 code to calculate and specify a payload length, i.e. payload truncation for normal packets sent to ports, at a byte granularity.  Such a value can be calculated without examining the entire payload, e.g. from the IPv4 Total Length field.

**Comment by vgurevich** [comment]
@jafingerhut ,

When the source send this TCP ACK out (from its TCP/IP stack), the driver or the Ethernet MAC will add padding (usually 0s) and after that once the 64-byte frame is out, it doesn't matter whether these 0s were just padding or not from the point of L2 and L3 devices. Once they reach a L4 or higher-level device/stack that actually cares about the contents of TCP payload, it can certainly remove the padding, but a regular L2/L3 switch would generally not. Obviously, P4 gives you a lot of flexibility in this are, but that's the general approach

**Comment by jafingerhut** [comment]
The point is that that padding can be preserved by a P4 device if it makes the packet larger, e.g. by adding a header.  But without some extra information, the P4 device has no way to know that those 6 bytes were padding to be removed, not part of the payload that should be kept.

Again, I don't have encyclopedic knowledge of whether any downstream devices will misbehave because of that.

**Comment by vgurevich** [comment]
@jafingerhut ,

Generally speaking this problem does happen every time you put additional headers onto the packet. It is not a problem with small packets like you described, but usually this is a problem with the MTU-sized packets: you add a header or two and suddenly the new packet exceeds the MTU. 

Thoroughly written data plane programs are supposed to be able to deal with that. For some protocols they can make the necessary determination at ingress and if they believe the egress packet will be longer than MTU, they'll send it to the control plane for fragmentation instead. In the worst case, egress packet length is generally available at the egress pipeline and  then they can  egress clone the final packet so that it gets to the CPU for fragmentation. 

Sending a 70 byte packet instead of a 64 byte packet should not be a problem.

The problem with short packets is decapsulation: you might remove a header or two and then the packet will be shorter than 64 bytes. That's where MAC will help by adding padding automatically.

**Comment by jnfoster** [comment]
Marking this as stalled...
