### ISSUE TITLE
Referencing direct counter in the dataplane

### ISSUE THREAD

**Issue by gldpittolzinho** [p4lang/p4-spec#594]
Is there a way to acquire the value of the direct counter that was incremented as a result of a match inside a table? 

I'm asking because I would like to compare the number of hits for an entry in a forwarding table (kept in the direct counter for that rule) against a threshold to assess how loaded a link is without having to maintain my own counting array and without imposing too much overhead on every packet that is processed.

**Comment by jnfoster** [comment]
No. If you need to read the value in the data plane, you should use a register.

**Comment by gldpittolzinho** [comment]
If there really isn't a way to access said values in the data plane I think that the case could be made for a possible addition. I do not see this new feature being harmful to any already put in place systems and I think the inclusion of a primitive for said kind of reading (reading the last incremented counter into a variable) would permit the efficient implementation of many load-aware systems. The physical implementation would be simple as well so I would like to share this thought.

**Comment by jafingerhut** [comment]
As Nate mentioned, you can use a P4 register to implement counters that are
readable from the P4 program, and affect how packets are processed.  You
can also implement many other stateful processing techniques using
registers.

Changing counters so that their values are visible from the P4 program _is_
a big change, as far as ASIC implementations go, especially ones that are
already done :-)  Common implementations do read-and-clear operations on
small wrapping or saturating counters in the fast path, and accumulate the
values in driver software outside of the ASIC.  Those read-and-clear
operations could happen at times that are not under the control of your P4
program, so counters could be going from N back down to 0 at unpredictable
times.

Andy

**Comment by gldpittolzinho** [comment]
Thank you for the clarification and for taking the time to elaborate. Closing the issue.
