### ISSUE TITLE
Is there any way to run VSS example in P4-16 spec chatper 5?

### ISSUE THREAD

**Issue by onlyfly34** [p4lang/p4-spec#597]
I'm trying figure out how to compile **very_simple_model.p4** and **vss-example.p4**.
I've found those two files in **p4c/testdata/p4_16_samples** directory. Trying to compile like exercises in **P4D2_2018_East/exercise/** do but doesn't work.

I'm new to P4-16 and hope to get some help. Thank you.

**Comment by jafingerhut** [comment]
The open source P4_16 compiler in https://github.com/p4lang/p4c can currently compile P4_16 programs using the architecture defined in the file v1model.p4 here: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4 and the open source simple_switch software switch can then forward packets from those compiled results.

There is work started recently to enhance p4c and behavioral-model so that they can use the recently-published PSA architecture specification, but that will likely not be ready for several more months.

I am not aware of anyone who has gone to the effort to modify p4c and behavioral-model to use the VSS architecture.  It was a simple architecture created to have a small specific architecture for the P4_16 language specification, but it does not have enough features to provide a strong motivation for implementing it.

**Comment by mbudiu-vmw** [comment]
Since vss is a strict subset of v1model, one could probably quite easily implement a source-to-source translator from vss to v1model based on the existing p4c compiler. The one can use bmv2 as an emulator of vss. This would be a nice simple project to learn p4c.

**Comment by mbudiu-vmw** [comment]
I don't think this is a spec issue, so I will close it.
