### ISSUE TITLE
Suggestion on inheriting operations for 'newtype' / 'type' types

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#616]
@mbudiu-vmw Feel free to copy this to an issue or PR you create, or I can do it if you let me know where you want it copied.  I just wanted to save this somewhere public after writing it up.

----------------------------------------
Operations on bit<> and int<> types ('b' for both, 'u' for unsigned bit<W> type only).

b = (assignment, passing as 'in', 'out', 'inout', or directionless parameter)
b ==
b !=
b < > <= >=
b - (unary)
b + (unary)
b + (binary)
b - (binary)
b * (binary)
u ~ (unary)
u & (binary)
u | (binary)
u ^ (binary)

u ++ (concatenate)
u [hi:lo] (slice)
b <<
b >>

b can be included as a field of a header type, with extract()
  lookahead() emit() methods working on those headers

Among those, my suggestion would be that a 'newtype' type would
automatically inherit all of those operations, except the ones
mentioned below.

Never inherit ++ or slice operations, because the results are usually
a different bit width than the operands, so the result could not be
the same type as the operands for new types derived from 'bit<8>', for
example.

Do inherit << and >>, but only with the new type as the left operand
(the value to be shifted), never the right operand (the shift amount).
The right operand would always be only the kinds of integer values
accepted by P4_16 today (compile-time known integer or bit<W>
expression).

For casts, suggest that we only allow cast to the 'base type', or from
the base type to the new type.

----------------------------------------
Operations on struct types:

* = (assignment, passing as 'in', 'out', 'inout', or directionless parameter)
* ==
* !=
* field access using "." notation
* Can be emit()'ed.

If we decide that later headers can contain some kinds of structs
within them, then 'newtype' derived struct types should also be usable
there.

Suggest that a 'newtype' would automatically inherit all of those operations.

----------------------------------------
If we support newtype / type derived from header, header_union, etc. I would suggest inheriting all operations.  Similar to struct, I cannot think of any that would need to behave differently for a newtype vs. the base type.

**Comment by mbudiu-vmw** [comment]
Let's try for a while without inheriting operations; once functions are working we can see whether they do a good enough job. Maybe we'll consider operator overloading.

**Comment by antoninbas** [comment]
I'd like to revisit this issue if possible.
We have a use case where we'd like to define some well-know types (e.g. `MacAddr_t`, `IPv4Addr_t`, ...) along with some architecture-specific types (e.g. `PortId_t`, just like in PSA) as user-defined types in our architecture file.
By defining them as user-defined types, we ensure that entities with these types are exposed in a nice way to control-plane applications. For a example, if a table matches on a field with type `MacAddr_t`, where `MacAddr_t` is a type defined in the architecture, one can write a CLI that accepts match values in the human-readable format commonly used for MAC addresses (`aa:bb:cc:dd:ee:ff`).
The restriction on the arithmetic operations supported by user-defined types is both a good thing (it is good to be able to disable non-sensical operations on some types) and bad thing (no operations at all are supported at the moment). A lot of programs I am familiar with use bit-slicing extensively on port values, which currently prevents us from using a custom type for ports as these expressions would quickly become nasty because of all the explicit casting required.

I understand that besides the new syntax that we need to introduce to support selectively inheriting operations, there are quite a few questions to answer. For example, in the case of slicing, what is the type of the result? @jafingerhut suggested never inheriting from the slicing and concatenating operations. But I don't think this is an option. In many cases, I would say that slicing is the most important operation to support, in addition to all the bitwise operations (`|`, `&`). One is more likely to slice a port or an IP address than increment them for example.

I don't have a concrete proposal on how to implement this inheritance mechanism, but now that we are getting more mileage out of user-defined types thanks to PSA & P4Runtime, maybe we can revisit this issue?

**Comment by jafingerhut** [comment]
So if you have `type bit<32> IPv4Addr` followed later by some header field or variable `IPv4Addr dstAddr`, what type would you want the _result_ of the expression `dstAddr[15:0]` to be?

It cannot be type `IPv4Addr`, because it is only 16 bits wide, true?

Would you suggest it be type `bit<16>`, as it would be if the value `dstAddr` had type `bit<32>`?

Would you expect slicing a value of type `PortId_t` to be useful in a portable way across targets?  Or do you think it is likely only useful with specific knowledge of a particular target?  The PSA specification, at least, does not give any requirements on what a subset of a value of type `PortId_t` could possibly mean, nor even that any particular bit position would even vary from one port to another (e.g. bit position 5 might always be 0 for all valid port numbers on a particular target).

**Comment by jnfoster** [comment]
Marking this as stalled. Speak up if you'd like to resurrect it.
