### ISSUE TITLE
Idle timeout

### ISSUE THREAD

**Issue by milad14000** [p4lang/p4-spec#617]
I was wondering how aging can be implemented in PSA. In the spec a new table property of ``` psa_idle_timeout``` is proposed but it's not clear how it can be used and it's not listed in ``` Table 6. Summary of PSA table properties.```

I assume it should be used like this?
```
table {
    actions = { NoAction }
    psa_idle_timeout = true;
}
```

**Comment by antoninbas** [comment]
We went with an enum for P4Runtime, so I hope the PSA property will match that.

**Comment by jafingerhut** [comment]
This issue was discussed in the last P4 Arch work group meeting on 2018-Aug-01.  The plan is that someone, perhaps @vgurevich, will write a proposed change to the PSA adding a description of how this idle timeout works.  At the very minimum, there will be a way to specify that a table has an idle timeout.  I hope the change also defines ways (at least optional ways) for the P4 source code to specify something like "I want this table to cause notifications to the P4Runtime client if table entries are not matched after 30 seconds, plus or minus 1 second", Such durations and time interval sizes could be used by a P4 compiler to choose a number of bits per table entry for "last matched time", for example (if an implementation chose to do it that way -- there are other variations of how to do it, but they all have finite durations and precisions on when the notification occurs).

**Comment by cc10512** [comment]
We should note in the text that the units for idle timeout can be a platform choice, rather than forcing to nano-seconds.

**Comment by jafingerhut** [comment]
Closing this issue now that this PR has been merged into the PSA spec: https://github.com/p4lang/p4-spec/pull/688

For anyone interested, please do read the changes and open separate issues if you have any comments/corrections.
