### ISSUE TITLE
Enhancement: p4c to support serializable error enum for use as table key

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4-spec#741]
It is useful to allow an `error`  to be a table key so that the Parser and Control can report errors to the control-plane.  Otherwise one has to use daisy-chained if-else statements (see https://github.com/p4lang/p4-spec/pull/739).

Any p4c control-plane changes regarding this issue would go into a P4Runtime 1.x future release.  In its current form, the `error` cannot be used as a table key by the data plane. This Issue proposes to develop a new `serErrorEnum` akin to `serEnum` defined internally by p4c.  An example of the new type is shown below.
```
error bit<8> ParserErrors {
    ParseError = 0x0, 
    PacketTooShort = 0x1
}
```
Any impact this p4c change have on, p4c API generation and p4runtime protobuf, will be tracked by an Issue to file later against p4lang/PI.

**Comment by jnfoster** [comment]
Recall from the [spec](https://p4.org/p4-spec/docs/P4-16-v1.1.0-spec.html#sec-the-error-type) that an `error` declaration adds a new member to the single, top-level `error` type. Because `error`s are "open to extension, it won't not easy to determine the width of an error, unless we pick 32 bits or something large enough for all practical purposes (but then some will complain that's too wasteful). It would also be hard to disambiguate between the serialized values introduced in different declarations in the code (e.g., standard library vs. user program).

**Comment by hesingh** [comment]
Good input.  It doesn't make sense to support both `error` and a new `serErrorEnum`.  Once kinks are ironed out for `serErrorEnum`, this could be the new error functionality in p4c.

Regarding disambiguate, with existing `error`, the user cannot add a duplicate value to the top-level `error`. Likewise, with new `serErrorEnum`, the same check is enforced without adding extra complexity.  There is extra work for p4c to maintain different serialized error enums.

Regarding 32 bits, what does `error` use today for internal storage?  The same storage type could be used for serializable error.

**Comment by hesingh** [comment]
I checked the p4c code for `error` and see an `int` being used.  In a few architectures, `int` is of size 32 bits.

**Comment by jafingerhut** [comment]
@hesingh The P4_16 language spec has so far been very explicit that it does not mandate how targets represent value of type `error`, or non-serializable `enum` values.  There are multiple members of the P4_16 language spec that may not wish to casually toss out this property, but I do not know the depth or strength of this opinion.  This property is of course exactly what makes things tricky when talking about how to put such values into packet header fields -- there is _no_ target-independent language-specified bit-wise representation for them.

Backwards-incompatible changes like eliminating the existing type `error` from the language are going to be very strongly resisted, I would guess, because of the desire not to break earlier programs written to older specs.  There have been public statements made that the LDWG will be very cautious before breaking backwards compatibility.

Asking what targets typically do may help guide discussions on the matter, but I suspect that many will not see target-specific implementations (not even BMv2) forcing the hand of the language specification.

I could imagine that for type `error`, the LDWG in a moment of group intoxication might agree to mandate in the language spec that `bit<8>` is enough for all targets, so let us add to the language spec that values of type `error` can be cast to/from values of type `bit<8>` on all targets.  Personally, I wouldn't even need to be intoxicated at all, but please do not think that I have the persuasive powers necessary to carry off such a feat. (just joking about the intoxication part -- we are a pretty sober bunch)

Even if nothing in the language spec changes, Antonin Bas has mentioned that he is in support of a future version of P4Runtime (after v1.0) enabling support for table search key fields, value_set key fields, and action parameters also allow other types, of which `error` and non-serializable `enum` values are probably high on the list.
+ https://github.com/p4lang/p4-spec/pull/739#discussion_r261696461
+ https://github.com/p4lang/p4runtime/issues/191

If a value of type `error` was supported by P4Runtime as a table search key field, then converting between values of type `error` and whatever `bit<W>` size you want in your program could be done via a single table lookup, as demonstrated in this example PSA program: https://github.com/p4lang/p4-spec/blob/master/p4-16/psa/examples/psa-example-parser-error-handling.p4#L221-L250

**Comment by hesingh** [comment]
Forgot about good-old backward compatibility!  Explicit Cast to bit<8> sounds reasonable to me.

**Comment by jafingerhut** [comment]
Note: Supporting an explicit cast from `error` to `bit<8>` is _also_ a change to the current language spec.  I was mentioning that as an idea.  It doesn't work today, and whether the LDWG would be interested in adding that to the spec is also unknown to me.
