### ISSUE TITLE
Qualified names in actionRef syntax?

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4-spec#780]
Not sure this is a bug but I'm confused by this example in [section 13.2.1.2](https://p4.org/p4-spec/docs/P4-16-v1.1.0-spec.html#sec-table-action-list).
> Each action in the list of actions for a table must have a distinct name—e.g., the following program fragment is illegal:
>
>```action a() {}
>control c() {
>    action a() {}
>    // Illegal table: two actions with the same name
>    table t { actions = { a; .a; } }
>}

p4c rejected the example with a parse error, rather than reporting something about actions with  a shared name. I tried modifying the example to only have `actions = { .a; }`, but that was also rejected by p4c. After taking a look at the grammar it seems like actionRefs are bare names, rather than qualified names. I was misled by the example, I think--maybe it could be removed or the syntax for actionRefs could be expanded?

**Comment by mbudiu-vmw** [comment]
This looks like a bug in the compiler rather than in the spec. Filed an issue with p4c.

**Comment by vgurevich** [comment]
Do we're really need qualified action names in the tables? Is there a good use case for them? I would argue that actions should always be in the same scope (i.e. in the same control) as tables.

Thanks, 
Vladimir

**Comment by jnfoster** [comment]
The use-case is modularity and code reuse: you already defined an action, say at the top level, that does what you want. You want to reference it in a table rather than having to redefine it in the current control. For example:
```p4
#include <core.p4>

//Architecture
control C();
package S(C p);

action a() { }

control D() {
  table t {
    key = {}
    actions = { a; }
  }
  apply {
    t.apply();
  } 
}

S(D()) main;
```
This code is valid P4 code, according to the current front-end. 

But now suppose we define an action `a` within `D` that shadows the top-level `a`:
```p4
#include <core.p4>

//Architecture
control C();
package S(C p);

action a() { }

control D() {
  action a() { }
  table t {
    key = {}
    actions = { a; }
  }
  apply {
    t.apply();
  } 
}

S(D()) main;
```
This program is accepted too (with a warning). But we might like to have a way to reference the top-level `a`.

Additionally, if we already allow a programmer to access other components using a qualified name, it makes the language more complex to have a special exception for actions that forbids it.

**Comment by vgurevich** [comment]
@jnfoster ,

You can certainly write this code, but the main reason it compiles is because it doesn't do anything. The action needs to operate on some headers or metadata and there are none at the top-level, since P4_16 does not have global variables. Thus, to be useful, the action `a()` must have at least one directional parameter and thus in the table definition it needs to be bound to the specific variables that it needs to operate on, e.g. 
```
action a(inout bit<8> ttl, bit<8> dec) { ttl = ttl |-| dec; }
...
control D() {
     table t  {
          ...
          actions = { .a(hdr.ipv4.ttl) @name("dec_ipv4_ttl"); }
     }
}
```
Note, that because you must bind the action to the specific variable(s), the `@name()a annotation is almost inevitable here. In fact, I'd probably suggest making it a syntactic feature, so that the tables could be declared like so:
```
     table t  {
          ...
          actions = {  dec_ipv4_ttl = .a(hdr.ipv4.ttl);
                              dec_ipv6_hopcount = .a(hdr.ipv6.hopcount); }
     }
```
So, that naming is one of the reasons I think that action names within tables should be local, although it also shows potential usefulness of the proposed feature.

Now, the other problem is when you try to refer to an action defined inside another control. That action can freely refer to any variable(s) which are in scope inside that control. In fact, that's how most of actions are written (and that's why directional parameters are relatively rare). Obviously, this creates a lot of problems, not only with shadowing, but with readability -- it will be difficult to understand the program, where a table from the control C1 can operate on variables which are in scope of the control C2, not to mention that it will break the basic "access controls" we have in P4.

So, my concern is that we are trying to introduce a syntactic feature, where the majority of possible uses are potentially not semantically valid.

**Comment by jnfoster** [comment]
It's true that we need to respect scope. But there are still many such useful actions. For example, an action that invokes `mark_to_drop` from `v1model.p4`. Do you really want to force every `control` that needs to drop packets to define an identical action just to invoke that primitive?

**Comment by vgurevich** [comment]
@jnfoster ,

First of all, `mark_to_drop` is not an action, but an extern function in v1model, but if it was, it would be is a very good case for the basic access controls afforded to us by P4_16.

Remember, that what it is doing is setting some intrinsic metadata (in case of v1model implementation of BMv2-simple_switch I believe it sets `standard_metadata.egress_port` to 511). If `standard_metadata` (or, at least, `standard_metadata.egress_port`) is not passed as a parameter to a given control, that control should not be able to invoke `mark_to_drop()`, at least in my opinion.

That's precisely why we have the following in https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4#L342 and I quote:
```
@deprecated("Please use mark_to_drop(standard_metadata) instead.")
extern void mark_to_drop();

/***
 * mark_to_drop(standard_metadata) is a primitive action that modifies
 * standard_metadata.egress_spec to an implementation-specific special
 * value that in some cases causes the packet to be dropped at the end
 * of ingress or egress processing.  It also assigns 0 to
 * standard_metadata.mcast_grp.  Either of those metadata fields may
 * be changed by executing later P4 code, after calling
 * mark_to_drop(), and this can change the resulting behavior of the
 * packet to do something other than drop.
 *
 * See
 * https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md
 * -- in particular the section "Pseudocode for what happens at the
 * end of ingress and egress processing" -- for the relative priority
 * of the different possible things that can happen to a packet when
 * ingress and egress processing are complete.
 */
extern void mark_to_drop(inout standard_metadata_t standard_metadata);
```

**Comment by jnfoster** [comment]
I never said `mark_to_drop` was an extern...

The point is that an action identical to this, 
```
action drop(inout standard_metadata_t sm) {
  mark_to_drop(sm);
}
```
that just wraps `mark_to_drop` so it can be invoked in a table shouldn't need to be defined in each control. 

For example, this code is accepted by the compiler.
```
#include <core.p4>

//Architecture
struct sm_t { }
control C(inout sm_t sm);
package S(C p);
extern void mark_to_drop(inout sm_t sm);

action drop(inout sm_t sm) { mark_to_drop(sm); }

control D(inout sm_t sm) {

  table t {
    key = {}
    actions = { drop(sm); }
  }
  apply {
    t.apply();
  } 
}

S(D()) main;
```
is accepted by the compiler.

In this case, we could debate whether the cost of threading through `sm` is less than defining an action within `D` that references it via lexical scope. I think it is a slightly better design, but reasonable people could disagree. But in a larger example, I think the benefits would be clearer.

**Comment by vgurevich** [comment]
@jnfoster ,

As you can see in your example, you had to bind the action `drop()` to the control's parameter `sm` and this typically requires the `@name()` annotation if you want the control plane API to be generated in a reasonable fashion. 

As I said, I can see the case for the actions defined at top level. One of the reasons for that is that these actions simply cannot access anything but their parameters (directional or directionless). However, the proposal calls for a lot more, because it would allow tables to access any actions inside anywhere. That's the most serious part of my concern.

**Comment by jnfoster** [comment]
I agree that referencing actions from other controls needs to be done with care -- i.e., we don't have closures in P4.

**Comment by vgurevich** [comment]
@jnfoster ,

> I never said `mark_to_drop` was an extern...

I never said you said that. You invoked `mark_to_drop()` in the context of our discussion about actions and thus I simply reminded you that `mark_to_drop()` is not an action, but an extern, that's all.

**Comment by jnfoster** [comment]
No problem :-)

**Comment by vgurevich** [comment]
So, perhaps a simpler proposal would be to use scoping rules. That will allow actions to be defined at the top-level only, which seems to be safe. If a control defines the action with the same name, normal rules will apply as well and we are done.

**Comment by jafingerhut** [comment]
Not trying to derail the existing conversation, nor necessarily address any part of it with my comment here.

The original issue involves the "." notation in naming things.  I believe the existing P4_16 language, and the p4c implementation of it, already allows a table within a control to refer to actions defined at the top level.  You can even do this without using the "." anywhere in the name of the action, _as long as there is no other thing with the same name, shadowing the globally defined action inside the control_.

If there is a global action named "foo" and a local action named "foo" inside of a control C, then I believe using "foo" by itself inside of a table definition inside of control "C" will always refer to the action "foo" inside of C (assume both actions have the same signature, if signatures are relevant, which I do not yet know if they are).

I believe that the "." notation allows one to write a table that refers to the global action "foo", even in the presence of a local action with the same name "foo".  If the table definition simply uses "foo", it must be the local action defined inside of the control.  If the table definition uses ".foo", that is an explicit reference by the programmer to the global one.

In that case, I believe that ".C.foo" and maybe also "C.foo" are explicit references to the "foo" defined inside of C, but I cannot think of a reason why a programmer would want to use those names when defining a table inside of "C".
