### ISSUE TITLE
Using compound types for keys and action data

### ISSUE THREAD

**Issue by vgurevich** [p4lang/p4-spec#829]
Here are some examples:
```
struct vlan_aware_mac_t {
    bit<12> vid;
    bit<48> mac_addr;
}

table dmac {
   key = {
        vlan_aware_mac : exact;   /* vlan_aware_mac_t vlan_aware_mac = { hdr.vlan_tag.vid, hdr.ether.dmac}; */
   }
   . . . 
}
```
(Yes, I do understand that not all match types would work, but both `exact` and `ternary` certainly would work nicely)

```
struct nexthop_t {
    mac_addr_t dmac;
    PortId_t port;
}

action set_nexthop(nexthop_t nh) {
    hdr.ethernet.dst_addr = nh.dmac;
    standard_metadata.egress_spec = nh.port;
}
```

I cannot see anything in the spec that prohibits that, but the compiler is definitely not happy: it insists that the key fields must have scalar types and that action data must be too. 

Any thoughts? 

Personally, I think that if we want to allow people to write reusable code, both would be quite nice, but at the same time the implications (esp. to the API) are significant.

**Comment by mbudiu-vmw** [comment]
These are bmv2 limitations, the spec allows that.

**Comment by vgurevich** [comment]
Thanks, @mbudiu-vmw. That's good.

I am afraid that the checks might've ended up in the common frontend code, though.

@antoninbas  -- what do you think P4Runtime-wise? Are you interested?

**Comment by jnfoster** [comment]
Can you provide a complete, runnable example so folks can more easily
verify and debug with p4test?

**Comment by vgurevich** [comment]
@jnfoster -- Given that the compiler does not  seem to support that yet and neither do the APIs, I can provide only a theoretical example. 

This is more like a forward-looking thing -- I am trying to decide what to do with the APIs,  and how to write more modular/reusable code (if you remember my previous discussions on a  related topic).

**Comment by mbudiu-vmw** [comment]
The compiler has no problems supporting this on targets that offer this capability.

**Comment by vgurevich** [comment]
OK, let me check internally, but my feeling was that the errors were coming from the frontend:
```
simple_l3_struct.p4(146): [--Werror=type-error] error: Key hdr.ipv4.dst_addr field type must be a scalar type; it cannot be struct ipv4_addr_t
        key = { hdr.ipv4.dst_addr : exact; }
                ^^^^^^^^^^^^^^^^^
simple_l3_struct.p4(129): [--Werror=legacy] error: Action parameter data has a type which is not bit<>, int<>, bool, type or serializable enum
    action send(send_t data) {
                       ^^^^
```

**Comment by mbudiu-vmw** [comment]
The first error is from the typeChecker, which is indeed in the front-end. I guess that the idea is that keys can have multiple fields, so there is no point allowing a key which is a struct: you can create fields for each struct field. 

We can certainly add some syntactic sugar to allow structured-valued keys; the most important question is what happens to the control-plane API for this case.

The second error is from the p4 runtime serializer.

**Comment by jafingerhut** [comment]
Attached is a complete example that tries to use a struct variable as a table key field, and p4test with no bmv2 back end nor P4Runtime API back end gives the indicated error message:
```
$ p4c --version
p4c 1.2.0 (SHA: 62fd40a0)

$ p4test try-struct-as-table-key.p4
try-struct-as-table-key.p4(72): [--Werror=type-error] error: Key s1 field type must be a scalar type; it cannot be struct my_struct1_t
            s1 : exact;
            ^^
```
[try-struct-as-table-key.p4.txt](https://github.com/p4lang/p4-spec/files/4314832/try-struct-as-table-key.p4.txt)

**Comment by vgurevich** [comment]
Thanks, @mbudiu-vmw . 

The point is that if this is allowed and supported and makes sense (from the standpoint of practical development) then we can push the APIs to support that (e.g. by allowing fields of the type struct).  Ultimately, I think this will be helpful, although I understand that there will be work involved.

**Comment by jafingerhut** [comment]
The P4Runtime API versions up through 1.1 made an explicit design choice, probably starting around early 2018 (I don't recall exactly when), to limit it to table key fields and action parameters with type `bit<W>`, or a few other very similar things (see the complete list in Section 21 "Known Limitations of Current P4Runtime Version" if you are curious -- https://p4.org/p4runtime/spec/v1.1.0/P4Runtime-Spec.html#sec-architecture-specific-table-extensions ) in order to get the first version out the door more quickly.

It is well known by the P4API working group members how to generalize this -- "just" change some of the Protobuf messages contents/formats.

The main decision point in doing this is: should it be done in a backwards compatible way, or should it be allowed to break backwards compatibility?

If it is done in a backwards compatible way, there is a software engineering concern that the message formats, documentation, and parts of the P4Runtime implementation code will contain cases for the current `bit<W>` restriction, while also handling the new more general types, side by side.

If it is done in a backwards incompatible way, then special cases for supporting `bit<W>` can be eliminated, keeping only the more general handling of a large set of P4_16 value types.  The main down side there are the software engineering and system deployment concerns of dealing with two incompatible versions of the API, where the older version 1.x would not disappear for some time after 2.x was introduced, and both would need to be supported for some unknown time.

Others in the P4 API working group would be better to ask what they think is the best way to go.  Me, I personally lean towards the "maintain backwards compatibility" as the lesser of two annoyances, but I'm not implementing that code :-)

**Comment by vgurevich** [comment]
@jafingerhut  -- thanks! That's what I suspected. 

My view is fairly simple: if there is a language feature that is useful, it's probably better if the control plane API supports it :)  Given that there are talks about big new change(s) in P4Runtime, it might make sense to put it on the radar (that's why I was mentioning @antoninbas before). As you can see, I am looking at other stuff, such as type annotations, etc. that I believe will lead to better control plane APIs and tools.

For now, the important things for me is to make sure that the spec is supportive (it is) and that the compiler front-end is supportive (looks like not quite yet). If P4Runtime folks decide to get onboard -- great, but that's independent, since there are other control plane APIs I need to worry about :)

**Comment by jafingerhut** [comment]
@vgurevich I don't know the implementation details of p4c here terribly well, but note that at least _some_ ways of implementing this in p4c would 'flatten' the struct into its separate fields before generating the control plane API.  If that approach was taken, no control plane API changes would be needed to support structs, because they would just be the separate fields as far as the control plane API was concerned.  You do get into questions of what the names of those fields ought to be by default, then, e.g. should it be "mystructA.field1", "mystructA.field2", "mystructA.nestedStructB.fieldX", "mystructA.nestedStructB.fieldY", etc.?

The other primary alternative is to "keep the structs around" in p4c's intermediate representation, at least up to the point that the control plane API is generated.  Then you need more general type support in the control plane API(s).

**Comment by vgurevich** [comment]
@jafingerhut -- correct. As @mbudiu-vmw said, it will be mostly syntactic sugar, but very useful one. 

But it is important not to flatten early, in my opinion :) or at least provide a choice. I would prefer the second option therefore.

**Comment by jafingerhut** [comment]
Note that this "not flattening too early" is very similar to the P4runtime translation annotation on `type` types.  You don't want the `type`s to be forgotten by the compiler before the control plane API is generated, even if they are forgotten in the compiler's internals after that point.  Again, I do not know all of the ins and outs and possibilities here, so something better than what we have today for P4runtime translation is almost certainly possible -- just not always easy to see which ways avoid gotchas and corner cases.

**Comment by vgurevich** [comment]
@jafingerhut -- precisely.

**Comment by jnfoster** [comment]
Closing this one in favor of #836. It will be linked from there.
