### ISSUE TITLE
Tables matching on structs

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#836]
@vgurevich mentioned in a recent conversation the thought of extending tables so that they could have key expressions that were struct types, as well as the more commonly implemented `bit<W>` and `int<W>` types.

This might open up all kinds of questions, of course, so I decided to create an issue to place questions and possible answers to them.

One thing to note that is perhaps a bit odd: The P4_16 language specification includes match_kind `exact`, `ternary`, and `lpm`, but I do not believe it ever defines what those mean anywhere, nor does it define what it means to have a mix of different match kinds for different keys in the same table.  I am not saying that this must be changed, but if the spec defines that it should be possible to match on a struct, then that raises questions like "if we want to define the behavior of those match_kinds on structs in terms of the behavior of similar match_kind on type `bit<W>`, should the behavior be defined for type `bit<W>` in the spec?"

Also the following questions come to my mind:

+ What other types can be matched on?  enum?  serializable enum?  error?  tuple?  header?  header_union?  bool?  varbit?  control?  parser?  package?  I believe the answer should be definitely yes for some, and definitely no for others, but if everyone actually already agreed on on the answers for all of those, _and_ what the behavior should be, I would gladly put $500 into a jar for the LDWG's use.

+ It seems to be fairly straightforward to define what it would mean to match on a struct that contained fields that were only type `bit<W>` and/or `int<W>`, or nested structs that bottomed out at those types, for match_kind `exact`, and also for `ternary`.  Also the newer `optional` one, too.  It isn't so clear to me that it makes sense to match on a struct with two or more fields and have a match_kind of `lpm` or `range`.  Should those match_kinds be disallowed if the key expression has a struct type?  If they are allowed, what should the definition of the behavior be?

A comment on some desired behavior regarding struct types as table keys:

+ One goal would be that it should be possible for an auto-generated control plane API to be aware of the struct types involved, and to somehow represent those struct types explicitly in the control plane API.  Values of such struct types can be represented in the P4Runtime API today, although in P4Runtime 1.2 and earlier, not for table keys, but that and similar things are on the table for discussion for P4Runtime 2.x (no release date planned for such a thing yet).  That is, while it is certainly possible for a P4 compiler to expand a struct as a table key into individual fields as a valid technique when optimizing for a particular target device, that should _not_ be done before generating the control plane API.

**Comment by vgurevich** [comment]
@jafingerhut -- thanks a lot for this thoughtful writeup.

I think that defining what each match kind does is a great idea! I know, I have to teach it in the class to the people who come in, claiming to already know the language :) so it will be useful irrespective of this particular issue.

I think we can also define the applicability of various standard match types in terms of applicability of basic operations. 

Specifically:
- `exact` and `optional` should be usable with any types that support equality (`==`)
- `lpm` should be usable with any type that supports bit slicing (`[u:l]`) in addition to equality
- `ternary` should be usable with any type that supports an AND operation(`&`) in addition to equality
- `range` should be usable with any type that supports less-than (or greater-than) (`<` and/or `>`) in addition to equality

I would also very much like to see `ternary` being applicable to structs and headers, which is fairly straightforward to define as long as we agree that is the structs/headers `s1` and `s2` have the same type and all their elements support the AND operation, then `s1 & s2` is the AND of their corresponding elements. Headers are the same, but also must be both valid.

**Comment by jafingerhut** [comment]
If you think you can say you wish to do ternary matching on headers, and _not_ be asked to be very explicit about what you expect the behavior to be in the cases where the variable containing the header being matched is invalid, and whether the control plane API can install an entry that means 'must be invalid', then I am disappointed you didn't anticipate such questions :-)

Are you thinking it would be as if the validity bit is one of the fields to match in the table search key, and the control plane API can install a 1-bit value and mask for that valid bit, too?

**Comment by vgurevich** [comment]
@jafingerhut -- I am not saying I didn't anticipate such questions, but I want to get a general consensus before spending my time arguing for something that people do not want to do.

With regards to header validity, no special rules are required, actually. One should be able to AND invalid headers as well as long as they do not expect any particular result in return.

**Comment by vgurevich** [comment]
Here are some basic definitions:

### A match for a single field `F` of type `<T>`

**Exact match** is available for any type <T> that support the checking for equality (`=`) operation. The table key consists of a field, usually named `F` of type <T>. The algorithm is:
```
table.hit=False;
table.miss = True;
for (key, action, data) in table.entries { /* Note, that the order of entries in indeterminate */
    if key.F == F {
       table.hit = True;
       table.miss = False;
       break;
   }
}
/* This is common for all tables */
if (table.hit) {
    /* Run action(data); */
else {
    /* Use default entry or NoAction() */
}
```
If a table has multiple entries with the same key, any of these entries will match. A driver may prevent this situation from happening by handing an attempt to install an entry with an already existing key in a special way, such as returning an error, overwriting the existing entry instead of creating a new one, etc.

**Optional**. I do not know much about how it got implemented, so I'll leave this for someone else.

**LPM**. This match kind is available for any type that supports bit slicing operation (and thus has distinct width W.  The result of bit slicing must support the equality (`=`) operation (which is always the case, currently). The table key corresponding to the field F consists of two components, e.g. F (of type <T> and F_prefix_length of a type, at least wide enough to hold the value W. F_prefix_length can have values in the range 0..W

The match algorithm is as follows:
```
table.hit=False;
table.miss = True;
for (key, action, data) in table.entries.sort(by=key.F_prefix_length, order=descending) {
    if (key.F.prefix_length == 0) {
       table.hit = True;
       table.miss = False;
       break;
    }
    if (key.F[W-1:W-key.F_prefix_length] == F[W-1:W-key.F_prefix_length]) {
       table.hit = True;
       table.miss = False;
       break;
    }
}
/* This is common for all tables */
if (table.hit) {
    /* Run action(data); */
else {
    /* Use default entry or NoAction() */
}
``` 
A stricter option, requiring the lower bits of key.F to be 0 can be added as it is a good practice. If a table contains multiple entries with the zero prefix length, the result is indeterminate (you do not know which one will hit). Again, see the note about the role of the driver/API above.

**Ternary**. This match kind is available for any type that supports the logical AND (`&`) and equality checking (`=`) operation. The table key that corresponds to the field F consists of three components. e.g. F (of type <T>) and F_mask (also of type <T>).  The third component is called priority (MATCH_PRIORITY) and must have a type that supports comparison operations, such as '<', '=', '>', i.e. allow sorting. The specific meaning of match priority is not regulated by the spec (i.e. the higher priority can be associated with numerically higher or lower numbers) and is left to the specific implementation.

The match algorithm is as follows:
```
table.hit=False;
table.miss = True;
for (key, action, data) in table.entries.sort(by=key.MATCH_PRIORITY /*, order=descending_or_ascending */) {
     if (key.F == (F & key.F_mask) {
       table.hit = True;
       table.miss = False;
       break;
    }
}
/* This is common for all tables */
if (table.hit) {
    /* Run action(data); */
else {
    /* Use default entry or NoAction() */
}
```
(A slightly weaker option, that allows "dirty" keys) would look like this:
```
     if ((key.F & key.F_mask) == (F & key.F_mask) {
```
Also, we can allow some implementations to have inverted masks if they so choose.

If multiple entries have the same key (key.MATCH_PRIORITY, key.F and key.F_mask), then the result is indeterminate (i.e. one of them will hit, but we do not know which one).

**Range match**. This match kind is available for any type that supports the comparison ('<=` or `>=` operations). The table key that corresponds to the field F consists of three components. e.g. F_min (of type <T>) and F_max (also of type <T>).  The third component is called priority (MATCH_PRIORITY) and must have a type that supports comparison operations, such as '<', '=', '>', i.e. allow sorting. The specific meaning of match priority is not regulated by the spec (i.e. the higher priority can be associated with numerically higher or lower numbers) and is left to the specific implementation.

The match algorithm is as follows:
```
table.hit=False;
table.miss = True;
for (key, action, data) in table.entries.sort(by=key.MATCH_PRIORITY /*, order=descending_or_ascending */) {
     if (key.F_min <= F && F <= key.F_max) {
       table.hit = True;
       table.miss = False;
       break;
    }
}
/* This is common for all tables */
if (table.hit) {
    /* Run action(data); */
else {
    /* Use default entry or NoAction() */
}
```
A slightly more powerful option might be to handle the situation where key.F_min >= key.F_max as a "wraparound" match
```
    if (key.F_min <= key.F_max) {
        if (key.F_min <= F && F <= key.F_max) {
           table.hit = True;
           table.miss = False;
           break;
        } 
    } else {
       if (F <= key.F_min || key.F_max <= F) {
           table.hit = True;
           table.miss = False;
           break;
        } 
    } 
```
Also, we can allow some implementations to have inverted masks if they so choose.

### A key consisting of multiple fields

If any of the fields in the key uses ternary or range match kind (that requires MATCH_PRIORITY), then the entry has to have MATCH_PRIORITY and lookup is performed in that order.

Note: this potentially allows combining LPM entries with ternary/range, although we do not currently use that.

If there are no keys with MATCH_PRIORITY, but there is a single field with `lpm` match kind, then the lookup is performed according to the prefix length.

Note: currently we state that no more than one field can use lpm match, but if desired, we can also add that for more than one field with lpm match_kind MATCH_PRIORITY is automatically added and that's the order for the lookup

In other cases, the lookup order is arbitrary.

The entry matches if the match condition is True for **each and every field**, specified in the key, according to the rules for an individual field above

### A match key of the compound type

For the compound types we have the equality operation, so they can certainly participate in the `exact` and `optional`. Bit-slicing is not defined for structs/headers, so no `lpm`. Greater-than and Less-than are also not defined, so no `range` match. 

However it is very easy to define an AND operation: it is a field-wise AND (provided that every field supports that, of course). If we do that, then `ternary` match works too.

**Comment by jafingerhut** [comment]
Looks mostly good to me.  For presentation, the concept and options on priority are best described once.

I don't think I can predict from what you have written how a ternary match on a header type is supposed to work.  If you say a valid header has a valid bit equal to 1, and invalid has valid=0, and extend the `&` operator to include the valid bit as another field, is that what you had in mind?  The only qualification I can see with that approach is that it would be anti-recommended to install a table entry that matched on valid=0, and in the same entry tried to match on any other field equal to a specific value.

**Comment by jafingerhut** [comment]
Also for presentation, seems like a good idea to only put hit in the pseudocode, leaving 'miss' behavior as a comment on the side that it is always the negation of 'hit'.

The comment on inverted masks for range match looks like copy/paste mistake.

**Comment by vgurevich** [comment]
Thanks for the review, @jafingerhut . I removed the copy-paste comment about the inverted masks from the range section. I agree with the fact that we can describe match priority separately and leave only hit or miss in the pseudocode -- I can do that when I create a PR.

As for the header match. which seems to be a somewhat controversial point (again!), here are my thoughts..
1) The "valid" bit is not a part of the header (at least yet)
2) Today, when we perform the match on the individual header fields, we do not require the header to be valid -- it is up to the programmer to check. We simply state that the result of the match will be indeterminate
3) Therefore, if we were to extend the concept to the whole header, I'd continue the same way - validity doesn't matter. The rule will work exactly the same way: if a header is invalid, then the result of the match is indeterminate. If someone wants to ensure that the header is valid, they can always add `hdr.h.isValid()` in the mix and I think that doing it explicitly is better.

**Comment by jafingerhut** [comment]
That idea of matching on an entire headers makes sense, and agreed that seems like the most consistent thing given current behavior on matching individual header fields.

**Comment by vgurevich** [comment]
@jafingerhut -- I edited my previous text a little and provided relatively simple rules for match_priority.

Perhaps, I should open a PR and we'll with it instead.

**Comment by jnfoster** [comment]
In the interest of tidying up the set of active issues on the P4 specification repository, I'm marking this as "stalled" and closing it. Of course, we can always re-open it in the future if there is interest in resurrecting it.
