### ISSUE TITLE
Should headers always be initialized as invalid?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4-spec#845]
Consider an action like `a1` below (the same questions apply for a header, header_union, or header stack local variable within a control, parser state, function, or block enclosed in curly braces inside the body of any of these things):
```
header h1_t {
    bit<8> f1;
    bit<8> f2;
}

control c1 () {
    action a1 () {
        h1_t h1;
        // Point A: what can we say must be true about the value of h1 here?
        if (h1.isValid()) {
            h1.f1 = 1;
            h1.f2 = 2;
        } else {
            h1.setValid();
            h1.f1 = 101;
            h1.f2 = 102;
        }
    }

    apply {
        a1();
    }
}
```
At point A in the program's execution, is there anything we can say about the value of h1 according to the language specification?

For example, can we say:

(a) At point A, it is guaranteed that `h1.isValid()` will return false.

Or is the following true?

(b) The return value of `h1.isValid()` undefined, and thus it is implementation-dependent whether it will return true or false, and might even return true when processing some packets, but false when processing other packets.

Or is there some third alternative that makes sense?

Here are parts of the P4_16 language specification version 1.2.0 that I think might be relevant, but my goal in creating this issue is to find out what people think ought to be true, and clarify the spec to match.

Section 7.2.2 "Header types" https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-header-types says: 'When a header is created its “validity” bit is automatically set to false.'  This seems to imply statement (a) above is true.

Section 10.2 "Variables" https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-variables says: 'Variable declarations without an initializer are uninitialized (except for header stacks, which have their nextIndex counter initialized to 0, as discussed in 8.16).'

and a little bit later in that same section 'Reading the value of a variable that has not been initialized yields an undefined result. The compiler should attempt to detect and emit a warning in such situations.'

That seems to imply statement (b) above is true.

There is a somewhat related issue involving direction `out` parameters that I will create separate from this one.  The questions raised in this issue seem to have nothing to do with parameters, only local variables with some header or header-like type.

**Comment by jafingerhut** [comment]
A reason why this issue might affect the cost of compiling programs: Imagine a case where the action `a1` in the code example of the original comment, or in general any control, parser, function, etc. is called more than once during the execution of a single top level parser or control.  If the answer is (a), then that implies that this local header variable needs to behave as if it is initialized to invalid on each separate call, not only once when the top level parser or control begins execution.

**Comment by vgurevich** [comment]
@jafingerhut -- this is a very thoughtful question and I am a little bit torn between these two options. Option (b) would allow a little bit more optimizations, while (a) is certainly more sane. Also, it is easier to choose (b) and then go to (a), while very difficult to choose (a) and then relax it to (b) 

We sort of went through the same experience with metadata initialization rules (in P4_14 metadata is initialized to 0 by default, while in P4_16 it is not) -- the rule definitely enabled more optimizations, but many people who were transitioning from P4_14 to P4_16 were initially surprised with some of the results.

Whichever the option we choose, I would assume that the practical effect (on the code that is already written that is) would be pretty negligible. 

First of all, 99.9% of all the headers are instantiated *by the architecture* and not by the user and thus are passed as parameters. If the parameter has the `out` direction, the spec explicitly says that though the header is uninitialized, it is set as invalid, right? If the parameter has `in` or `inout` direction then the architecture is free to initialize it any way it pleases :)

For the remaining 0.1% or less, people can always initialize the header with either `...` or `{...}` or simply leave it alone. In the latter case, additional optimizations will be possible. For example, your might want to use an explicitly instantiated header when you you want to convert between two headers, which are a member of a header union (e.g. convert IPv4 <=> IPv6). Since both cannot exist at the same time, you might copy the source header into an explicitly instantiated one inside an action, make the other header inside a union valid and then copy the values out. In most such cases validity check will not be used and optimized out. 

The other place where we need to be very mindful about the effects is the deparser (we do not want to emit garbage, obviously). However, the deparser gets the headers from the arch as an `in` parameter. If headers are explicitly instantiated in the deparser then it should not be a big deal to require their initialization -- I doubt any programs people have today will be affected.

So, as long as we keep the rule for the "out" parameters as it is today, we can go with (b).

**Comment by jafingerhut** [comment]
Yes, the current spec does say that direction `out` parameters that are headers must be initialized to invalid.  See https://github.com/p4lang/p4-spec/issues/846

That does cover the case of predictably initializing headers in any parser that has its header parameter with "type H" as direction `out`, which is most that I have seen, and hopefully most architectures I haven't seen, too.

I would guess that choosing option (b) would have no effect on the behavior of most existing P4_16 programs.  I created the issue primarily so the spec could be made more explicit about it than it is now, and more internally consistent with what it says in different sections.

**Comment by vgurevich** [comment]
Frankly, the current rule that you reference could've been easily eliminated if we agreed that headers should be `inout` instead of `out`.

In fact, that's pretty much what is happening, since we state that they somehow come in "pre-initialized" and we could've simply stated that the arch pre-initializes the headers this way and that's it.

Unfortunately, it is too late, because this change will break each and every program :(

**Comment by mbudiu-vmw** [comment]
Even if the architecture has some rules on the usage of headers regarding the input/output to the parser and controls, users can always define new variables of type headers and use them in any way they want. So the language spec has to describe how these are handled.

**Comment by jafingerhut** [comment]
Created PR #850 to attempt to resolve this issue, as discussed during 2020-May-04 LDWG meeting.

**Comment by jafingerhut** [comment]
This PR was merged: https://github.com/p4lang/p4-spec/pull/850
hence closing this issue as resolved.
