### ISSUE TITLE
Get both ingress and egress queue length in bytes 

### ISSUE THREAD

**Issue by suniljha555** [p4lang/p4-spec#859]
How do i get queue size in bytes? I tried some approaches, one of which was that i stored a 32 bit field in metadata. And as we know that in v1model switch each packet has to pass through parser, ingress pipeline,traffic manager, egress pipeline and deparser. I updated it with the packet_length field in ingress and egress block, but it always gave output as zero. Code is as follows:
`meta.que_len=meta.que_len+standard_metadata.packet_length;
meta.que_len=meta.que_len-standard_metadata.packet_length;`
when queue is build up (i generated UDP traffic using iperf), then shouldn't it give the queue length in bytes?
And can someone please explain how do we calculate queue size in v1model switch.

Thank you

**Comment by jafingerhut** [comment]
In the open source v1model architecture, there is no built-in mechanism to get queue sizes in bytes.

There are built-in mechanisms where during egress processing, you can read the depth of the queue a packet went through after ingress, and before egress, both at the time it was enqueued (standard_metdata.enq_qdepth) and at the time it was dequeued (standard_metadata.deq_qdepth).  The units of these queue depths are in number of packets, though, not in number of bytes.  Search for occurrences of qdepth on this page: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#queueing_metadata-header

There are other proprietary architectures that enable reading similar values in egress, in units that are either bytes, or more closely related to bytes, e.g. some architectures use "cells" as something approximately like "ceiling(packet_length_in_bytes / cell_size_in_bytes)", where cell_size_in_bytes might be a number like 60 bytes.  You would need to consult the documentation of the particular architecture to find out what they provide.

It is certainly possible using a fairly decent amount of P4 code, and packet recirculation, and P4 registers, to maintain a queue depth in any units you wish, readable from ingress.  Such a value would not be the most up-to-the-nanosecond correct value.  For example, it could be something like "exact total number of bytes ever enqueued in queue number X, minus a the number of bytes ever dequeued from queue number X as of between T1 and T2 microseconds ago", where T1 and T2 would depend upon details of the implementation, but could probably be made on the order of T1 approximately 1 microsecond, and T2 approximately 2 microseconds, on some high speed targets.

**Comment by jafingerhut** [comment]
Here is an issue on the behavioral-model repository suggesting the idea of adding variants of enq_qdepth and deq_qdepth to the open source BMv2 simple_switch implementation, which would not be a lot of work to implement, but it isn't necessarily an urgent thing to implement, either.  https://github.com/p4lang/behavioral-model/issues/841

Note that this repository where you have created this issue is intended for issues about the P4 language itself.  Up to this point, the kinds of features you are asking about have not been considered part of the P4_16 language specification, but are instead delegated to P4_16 architectures, and each such P4_16 architecture makes its own independent decisions what kinds of features like this that they provide.
