### ISSUE TITLE
Question on parser loops

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4-spec#881]
Have been looking at the parser lately. This is a slightly modified version of issue [692](https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/issue692-bmv2.p4). Is this a potentially infinite parser loop?

```p4
struct H { T[2] hstack; }

parser ParserI(packet_in b, out H parsedHdr, inout M meta, inout std_meta_t
    std_meta) {
    state start {
      b.extract(parsedHdr.hstack.next);
      transition p0;
    }
    state p0 {
      transition select(parsedHdr.hstack.next.y) {
      0: p0;
      _: accept;
      }
    }
}
```
Based on the discussion in #832 my assumption is that only `extract` and `pop_front`/`push_front` modify the index.

**Comment by vgurevich** [comment]
@fruffy -- selecting on the contents of `next` is a really bad idea, since by definition `next` is an **invalid** member of the stack. The compiler should be flagging such as select with at least a warning. 

Separately from that, it is clear that if you continue to select on the same thing without changing any other state in between, you will have an infinite loop. Again, the compiler should notice that the parser state p0 does not perform any operations that can affect the select condition and thus it it is true, it will remain true forever.

**Comment by fruffy** [comment]
Sounds good, thanks. As far as I can tell the compiler emits a warning for the invalid select read. However, no warning is emitted for the loop. Might be tricky to evaluate? 

```
modules/p4c/testdata/p4_16_samples/issue692-bmv2.p4(21): [--Wwarn=uninitialized] warning: parsedHdr.hstack.next: reading uninitialized value
      transition select(parsedHdr.hstack.next.y) {
                        ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mbudiu-vmw** [comment]
I believe that the loop unrolling pass used to detect such cases, but it's commented out (and buggy).
